name: al_murafiq
description: A new Flutter application.
version: 1.1.1+22

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.4
  # connectivity_plus: ^2.3.0
  rxdart: ^0.27.3
  get_it: ^7.2.0
  http: ^0.13.4
  dynamic_themes: ^1.1.0
  flutter_swiper_null_safety: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_phoenix: ^1.0.0
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  font_awesome_flutter: ^10.1.0
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.1.0
  intl_phone_number_input: ^0.7.0+2
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  flutter_advanced_networkimage_2: ^2.0.1
  rounded_loading_button: ^2.1.0
  carousel_slider: ^4.1.1
  multiselect_formfield: ^0.1.7
  awesome_dialog: ^2.2.0
  animator: ^3.1.0
  intl: ^0.17.0
  flutter_swiper_tv: ^1.1.6-nullsafety
  readmore: ^2.1.0
  smooth_star_rating_nsafe: ^1.0.0+1
  map: ^1.0.0
  google_maps_controller: ^1.2.0
  flutter_dropdown: ^1.0.0+hotfix.1
  easy_rich_text: ^1.0.4
  marquee: ^2.2.1
  rflutter_alert: ^2.0.4
  material_design_icons_flutter: ^5.0.6595
  flutter_login_facebook: ^1.4.1
  date_time_picker: ^2.1.0
  google_maps_flutter: ^2.1.3
  file_picker: ^4.5.1
  image_picker: ^0.8.5
  map_launcher: ^2.2.1+2
  firebase_messaging: ^11.2.14
  flutter_local_notifications: ^9.4.1
  google_sign_in: ^5.3.0
  flutter_share: ^2.0.0
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.9
  get: ^4.6.1
  geolocator: ^8.2.0
  dropdown_search: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  animate_do: ^2.1.0
  flutter_webview_plugin: ^0.4.0
  date_field: ^3.0.0
  flutter_downloader: ^1.7.3
  permission_handler: ^9.2.0
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  flare_flutter: ^3.0.2
  rive_loading: ^0.1.2
  android_intent_plus: ^3.1.1
  new_version: ^0.3.0
  sign_in_with_apple: ^3.3.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter



dependency_overrides:
  flutter_svg: ^1.0.3


#  to add icon for app
#  to run => flutter pub run flutter_launcher_icons:main

#    to add icon and color to splash screen
#    to run => flutter pub pub run flutter_native_splash:create

flutter:
  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
    - family: IBMPlexSansArabic
      fonts:
        - asset: fonts/IBMPlexSansArabic-Light.ttf
    - family: ltbukra
      fonts:
        - asset: fonts/ltbukra-Regular.ttf
        - asset: fonts/ltbukra-Bold.ttf
          weight: 200

  uses-material-design: true
