// ignore: always_specify_types
const Map<String,String> ar={
  'Download':'تحميل',
  'read':'أقرأ',
  'active_code':'تفعيل',
  'enter':'إدخل',
  'enter_rate':'الرجاء إدخال المعدل',
  'Male': 'ذكر',
  'Female': 'أنثى',
  'text_online-payment': 'أختيار الطريقة المناسبة للدفع عبر الإنترنت',
  'quit_app':'هل أنت متأكد من أنك تريد الخروج؟',
  'Exit':'خروج',



  'select_country': 'أختر دولة',
  'select_company': 'أختر شركة',
  'p_choose_country': 'من فضلك أختر البلد الذى تعيش فيه',
  'p_choose_company': 'أي شركه تريد تجديد الاشتراك لها',
  'select_language':' اختر لغة',
  'bt_done': 'تم',
  'login': 'تسجيل دخول',
  'search': 'بحث',
  'search_error': 'من فضلك أدخل كلمة للبحث',
  'no_data': 'لا توجد بيانات حالياً',
  'read_more': 'أقرأ المزيد',
  'read_less': 'أقرأ اقل',
  'al_murafiq': 'المرافق',
  'are_you': 'هل انت؟',
  'new_user': 'مستخدم جديد',
  'Marketer': 'مسوق',
  'dealer': 'شركة',
  'question_login': 'هل لديك حساب؟',
  'new_account': 'حساب جديد',
  'personal_info': 'معلومات شخصية',
  'account_details': 'تفاصيل الحساب',
  'profile_photo': 'صورة شخصية',
  'Company_photo': 'لوجو الشركة',
  'text_full_name': 'الاسم بالكامل',
  'text_full_name_error': 'يجب إدخال الإيميل',
  'hint_name': 'المرافق',
  'text_country': 'الدولة',
  'text_defalut_languages': 'اللغة الإفتراضية',
  'text_resturant': 'الشركة',
  'text_select_Pdf': 'أضف ملف',
  'text_df_language': 'اللغة الإفتراضية',
  'text_gender': 'النوع',
  'text_birthDate': 'تاريخ الميلاد',
  'text_national_id':' رقم الهوية ',
  'text_email': 'البريد الإلكترونى',
  'text_days': 'أيام',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'الرقم السرى',
  'text_confirm_pass': 'تأكيد الرقم السرى',
  'text_phone': 'رقم الهاتف',
  'text_phone_error': 'هذا الهاتف غير صحيح',
  'bt_continue': 'أكمل',
  'bt_submit': 'أضف',
  'text_place_name': 'أسم الشركة',
  'text_place_name_error': 'أدخل أسم الشركة',
  'text_description': 'التفاصيل',
  'text_description_error': 'أدخل التفاصيل',
  'text_address': 'العنوان',
  'text_add_address': 'أضف عنوان',
  'text_address_error': 'أدخل عنوان',
  'text_phone2': 'رقم موبايل آخر',
  'text_Tel': 'رقم أرضى',
  'text_fax': 'رقم الفاكس',
  'text_fax_error': 'رقم الفاكس غير صحيح',
  'you_must_login_to_access': 'من فضلك قم بتسجيل الدخول',

  'company_photo': 'صورة الشركة',
  'text_workdays': 'أيام العمل',
  'text_time_of_work': 'أوقات العمل',
  'text_category': 'التصنيفات',
  'select_city': 'اختر مدينة',
  'select_category': 'أخر تصنيف',
  'select_sub_category': 'أختر تصنيف فرعى',
  'side_eshtrakaty': 'الأشتراكات',
  'side_ads': 'الأعلانات المميزة',
  'side_social': 'السوشيال ميديا',
  'side_search_store': 'سجل البحث',
  'side_edit_profile': 'تعديل الحساب',
  'side_edit_company': 'تعديل الشركة',
  'side_mybranches': 'فروعى',
  'side_ask': 'الدعم الفنى',
  'side_policy': 'البنود و الأحكام',
  'side_total_client': 'العملاء',
  'side_notifications': 'الإشعارات',
  'side_who_us': 'من نحن',
  'side_logout': 'تسجيل خروج',
  'side_customers': 'عملاء',
  'title_resturant': 'مطعم',
  'text_open_Now': 'مفتوح الآن',
  'text_close': 'مغلق الآن',
  'text_special_mark': 'ملاحظات',
  'text_special_mark_error': 'أدخل ملاحظاتك',
  'text_reviews': 'التعليقات',
  'bt_leave_review': 'أترك تعليق',
  'bt_leave_review_error': 'أدخل تعليقك',
  'bt_leave_report': 'أترك مشكلتك',
  'bt_leave_report_error': 'أدخل مشكلتك',
  'text_done_report': 'تم إرسال المشكله بنجاح',
  'text_see_more': 'أقرأ المزيد',
  'text_more': 'المزيد',
  'text_done_review': 'تم تسجيل رأيك بنجاح',
  'text_under_reiew': 'تقييمك تحت المراجعة  شكرا لك',
  'text_your_plan': 'خططك',
  'text_your_plan_select': 'تم تحديد خطة لعملك',
  'bt_change_plan': 'تغيير الباقة',
  'bt_change_photo': 'تغيير الصورة',
  'bt_profile_photo':' الصورة الشخصية',
  'bt_add': 'أضف',
  'bt_cancel': 'إلغاء',
  'bt_check_out': 'تأكيد الطلب',
  'bt_edit': 'تعديل',
  'bt_edit_bran': 'تعديل',
  'text_technical_support': 'الدعم الفنى',
  'text_add_branch': 'أضف فرع',
  'text_add_ticket': 'أضف تذكرة',
  'text_add_social': 'أضف موقع تواصل',
  'text_social': 'موقع التواصل',
  'hint_link': 'رابط',
  'link_error': 'هذا الرابط غير صحيح',
  'hint_subject': 'الموضوع',
  'hint_subject_error': 'أدخل موضوع',
  'hint_details': 'التفاصيل',
  'hint_details_error': 'أدخل تفاصيل',
  'bt_send': 'أرسل',
  'hint_your_problem': 'أضف مشكلتك هنا',
  'text_forget_pass': 'هل نسيت كلمه السر؟',
  'text_set_email': 'أضف بريدك الأكترونى',
  'text_enter_code': 'من فضلك أدخل الرمز ',
  'text_change_email': 'تغيير البريد الاكترونى؟',
  'text_code': 'الرمز',
  'hint_code': 'يجب أن يكون 6 أرقام',
  'bt_sure': 'تأكيد',
  'text_enter_new_pass': 'من فضلك أدخل كلمة السر الجديدة',
  'text_new_pass':' كلمة سر جديدة',
  'text_success_change_pass': 'تم تغيير كلمة السر بنجاح',
  'side_be_delegate': 'كن مسوق',
  'side_be_company': 'كن شركة',
  'side_be_affilator': 'كن مسوق',
  'side_be_delegat': 'كن شركة',
  'side_contactus': 'تواصل معنا',
  'bt_add_plan': 'أضف خطتك',
  'bt_be_delegat': 'كن مسوق',
  'text_choose-payment': 'أختر طريقة الدفع المناسبة',
  'text_offline-payment': 'أختر الطريقة المناسبة للدفع الأوفلاين',

  'text_last_company': 'المضاف مؤخراً',
  'text_review':  'التعليقات',
  'text_all_categories':  'كل التصنيفات',
  'text_code_afflet':  'كود المسوق',
  'text_pass_not_similer':  'الرقم السري غير متطابق',
  'text_p_select_photo':  'أختر صورة  ثم حاول مرة اخري',
  'side_language_country':  'تغير لغة & دولة',
  'bt_change': 'تغيير',
  'you_must_sub': 'يجب إعاده الأشتراك',

  'message': 'الرسائل',
  'big-text1': 'من فضلك أدخل الأيميل',
  'big-text2': 'من فضلك, ادخل الكود',
  'big-text3': 'من فضلك أدخل الرقم السري الجديد',
  'again': 'تغيير البريد الإلكتروني؟',
  'number': 'رقم الهوية الوطنية ',
  'number_error': 'يجب أن يكون 14 رقمًا',
  'e': 'حدث خطأ ما حاول مرة أخري',
  'Loading': 'تحميل',
  'facebook': 'فيس بوك',
  'twitter': 'تويتر',
  'instagram': 'أنستجرام',
  'whatsapp': 'واتس آب',
  'snapshat': 'سناب شات',
  'googleplus': 'جوجل بلس',
  'website': 'موقع الكتروني',
  'other': 'آخر',
  'text_document': 'ملف الشركة',
  'text_go': 'أذهب إلي ',
  'text_select_country_msg': 'تأكد من أختيار الدولة والمدينة',
  'text_select_categore_msg': 'تأكد من أختيار الصنف',

  'face login': 'تسجيل الدخول بأستخدام الفيسبوك',
  'google login': 'تسجيل الدخول عبر جوجل',
  'are you': ' هل أنت ؟',
  'new account': 'حساب جديد',
  'language': 'لغة',
  'birth': 'تاريخ الميلاد',
  'cont': 'أستمر',
  'password': 'الرقم السري',
  'enter-pass': 'الرقم السري',
  'new pass': 'رقم سري جديد',
  're-pass': 'تأكيد الرقم السري',
  'phone': 'هاتف',
  'change': 'تغيبر',
  'online': 'عبر الإنترنت',
  'offline': 'طرق دفع أخري',
  'pass_error': 'يجب أن تكون كلمة المرور أكثر من 8 خانات',
  'promo_code': 'كود الخصم',
  'promo_code_used': 'كود الخصم مستخدم',
  'promo_code_accept': 'كود الخصم سليم',
  'sub_total':'التكلفة',
  'discount': 'خصم',
  'price': 'التكلفة الكلية',
  'Saturday':'السبت',
  'Sunday':'الأحد',
  'Monday':'الإثنين',
  'Tuesday':'الثلأثاء',
  'Wednesday':'الأربعاء',
  'Thursday':'الخميس',
  'Friday': 'الجمعة',
  'to':'إلي',

  'change-mail': 'تغيير البريد',
  'online-payment': 'الدفع عبر الإنترنت',
  'offline-payment': 'طرق دفع أخري',
  'how': 'كيف',
  'bank': 'البنك',
  'kash': 'نقدياً',
  'forgot_password?': 'هل نسيت كلمة المرور؟',
  'please_wait': 'أنتظر من فضلك..',
  'ok': 'حسنًا',
  'email_error': 'أدخل بريد إلكتروني متاح ',
  'details_error': 'يجب ألا تكون التفاصيل فارغة ',
  'code_error': 'يجب أن يكون الرمز أكثر من 6أرقام',
  'pay1': 'أختر خطتك للدفع',
  'pay2': 'أختر الباقة المناسبة لعملك الشهري',
  'plan2': 'أختر هذه الخطة',
  'do2': 'عدد السلايدر',
  'do3': 'عدد البنارات',
  'my-plan1': 'خطتك',
  'my-plan2': ' تغيير هذه الخطة',
  'my-plan3': 'الباقة المختارة لعملك الشهري',
  'eshtrak': 'بداية الأشتراك',
  'tagdeed': 'موعد التجديد',
  'bank1': 'المعلومات المناسبة\n للتحويل المصرفي',
  'bank2': 'المعلومات المطلوبة للحساب المصرفي',
  'bank_info_1': 'أسم البنك',
  'bank_info_2': 'رقم الحساب',
  'bank_info_3': 'أسم صاحب الحساب',
  'bank_info_4': 'أسم الفرع',
  'bank_info_5': 'رمز سريع',


  'text_select_time_msg': 'تاكد من اختيار لوقت',
  'select_time':'إختار الوقت',
  'show_photo':'عرض الصورة'
};