// ignore: always_specify_types
const Map<String, String> de = {
  'Download': 'Downloaden',
  'read': 'Lezen',
  'active_code': 'Actieve',
  'enter': 'Voer',
  'enter_rate': 'voer het tarief in',
  'Male': 'Mannelijke',
  'Female': 'Vrouwelijke',
  'text_online-payment': 'kies de juiste methode voor online betaling',
  'quit_app': 'Weet je zeker dat je weg wilt?',
  'Exit': 'Afsluiten',


  'text_select_time_msg':'Zorg ervoor dat u de tijd kiest',
  'select_time':'Termijn',
  'show_photo':'De afbeelding weergeven',
  'select_country': 'Kies een staat.',
  'select_company': 'Kies een bedrijf',
  'p_choose_country': 'Kies het land waarin u woont',
  'p_choose_company': 'Welk bedrijf dat zijn abonnement wil verlengen',
  'select_language': 'Kies een taal.',
  'bt_done': 'Gedaan',
  'login': 'Aanmelden',
  'search': 'Zoek',
  'search_error': 'Voer een zoekwoord in.',
  'no_data': 'Er zijn momenteel geen gegevens',
  'read_more': 'Lees meer',
  'read_less': 'Lees minder',
  'al_murafiq': 'Al_Murafiq',
  'text_more': 'Meer',
  'are_you': 'Ben je dat?',
  'new_user': 'Nieuwe gebruiker',
  'Marketer': 'Marketeer',
  'dealer': 'Een bedrijf',
  'question_login': 'Heb je al een account?',
  'new_account': 'Nieuw account',
  'personal_info': 'Persoonlijke informatie',
  'account_details': 'Accountgegevens',
  'profile_photo': 'Profielfoto',
  'Company_photo': 'Logo bedrijf',
  'text_full_name': 'De volledige naam.',
  'text_full_name_error': 'De e-mail moet worden ingevoerd.',
  'hint_name': 'murafiq',
  'text_country': 'De steun van de regering',
  'text_defalut_languages': 'Virtuele taal',
  'text_resturant': 'Bedrijf',
  'text_select_Pdf': 'Een bestand toevoegen',
  'text_df_language': 'Virtuele taal',
  'text_gender': 'Geslacht',
  'text_birthDate': 'Geboortedatum',
  'text_national_id': 'ID-nummer ',
  'text_email': 'E-mail',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'Wachtwoord',
  'text_confirm_pass': 'Bevestig het pinnummer',
  'text_phone': 'Vana',
  'text_days': 'Dagen',
  'text_go': 'Ga naar',
  'text_phone_error': 'Deze telefoon is niet goed.',
  'bt_continue': 'Blijven',
  'bt_submit': 'Opslaan',
  'text_place_name': 'Bedrijfsnaam',
  'text_place_name_error': 'Voer de bedrijfsnaam in.',
  'text_description': 'Details',
  'text_description_error': 'Voer de gegevens in',
  'text_address': 'Adres',
  'text_add_address': 'Een titel toevoegen',
  'text_address_error': 'Voer een adres in',
  'text_phone2': 'Nog een mobiel nummer.',
  'text_Tel': 'Landnummer',
  'text_fax': 'Faxnummer',
  'text_fax_error': 'Het faxnummer is onjuist.',
  'you_must_login_to_access': 'Meld u aan.',
  'you_must_sub': 'U moet een abonnement nemen ',
  'company_photo': 'Bedrijfsfoto',
  'text_workdays': 'Werkdagen',
  'text_time_of_work': 'Werktijden',
  'text_category': 'Categorieën',
  'select_city': 'Kies een stad.',
  'select_category': 'Kies beoordeling',
  'select_sub_category': 'Kies een subclassificatie',
  'side_eshtrakaty': 'Abonnementen',
  'side_ads': 'Speciale aankondigingen',
  'side_search_store': 'zoekplaats',
  'side_edit_profile': 'Profiel bewerken',
  'side_notifications': 'Meldingen',
  'side_social': 'Sociale links',
  'side_edit_company': 'Bedrijf bewerken',
  'side_mybranches': 'Mijn vestigingen',
  'side_ask': 'Technische ondersteuning',
  'side_policy': 'Algemene voorwaarden',
  'side_total_client': 'Klant',
  'side_who_us': 'Informatie',
  'side_logout': 'Aangemeld',
  'side_customers': 'Klant',
  'title_resturant': 'Restaurant',
  'text_open_Now': 'Nu openen',
  'text_close': 'Sluiten',
  'text_special_mark': 'Beoordelingen',
  'text_special_mark_error': 'Voer uw notities in',
  'text_reviews': 'Opmerkingen',
  'bt_leave_review': 'Ik laat een reactie achter.',
  'bt_leave_review_error': 'voer uw opmerking in',
  'bt_leave_report': 'Laat je probleem achter.',
  'bt_leave_report_error': 'voer uw rapport in',
  'text_done_report': 'Het probleem is met succes verzonden',
  'text_see_more': 'bekijk meer',
  'text_done_review': 'Uw mening is met succes vastgelegd',
  'text_under_reiew': 'Uw beoordeling is bewerkt.',
  'text_your_plan': 'Plannen',
  'text_your_plan_select': 'Er is een plan opgesteld voor uw bedrijf.',
  'bt_change_plan': 'Dit plan wijzigen',
  'bt_change_photo': 'De afbeelding wijzigen',
  'bt_profile_photo': 'Profielfoto',
  'bt_add': 'Toevoegen',
  'bt_cancel': 'Annuleren',
  'bt_check_out': 'Verzoek bevestigen',
  'bt_edit': 'Update',
  'bt_edit_bran': 'Bewerken',
  'text_technical_support': 'Technische ondersteuning',
  'text_add_branch': 'Vertakking toevoegen',
  'text_add_ticket': 'Een ticket toevoegen',
  'text_add_social': 'Een communicatiesite toevoegen',
  'text_social': 'Netwerksite',
  'hint_link': 'Link',
  'link_error': 'Deze link is onjuist.',
  'hint_subject': 'Onderwerp',
  'hint_subject_error': 'Een thema invoeren',
  'hint_details': 'Details',
  'hint_details_error': 'Details invoeren',
  'bt_send': 'Verzenden',
  'hint_your_problem': 'Voeg hier uw probleem toe',
  'text_forget_pass': 'Ben je het wachtwoord vergeten?',
  'text_set_email': 'Set your Email',
  'text_enter_code': 'Voer de code in!',
  'text_change_email': ' deze e-mail wijzigen?',
  'text_code': 'Code',
  'hint_code': 'Het moeten zes cijfers zijn.',
  'bt_sure': 'Bevestiging',
  'text_enter_new_pass': 'Voer het nieuwe wachtwoord in',
  'text_new_pass': 'Nieuw wachtwoord',
  'text_success_change_pass': 'Het wachtwoord is gewijzigd',
  'side_be_delegate': 'Marketeer zijn',
  'side_be_company': 'Wees een bedrijf',
  'side_be_affilator': 'Marketeer zijn',
  'side_be_delegat': 'Wees een bedrijf',
  'side_contactus': 'neem contact met ons op',
  'bt_add_plan': 'Een plan toevoegen',
  'bt_be_delegat': 'Wees een marketeer.',
  'text_choose-payment': 'Kies de juiste betaalmethode',
  'text_offline-payment': '  Kies de juiste methode van offline betaling',
  'text_last_company': 'Recent toegevoegd',
  'text_review': 'Beoordelingen',
  'text_document': 'Bedrijfsdocument',
  'text_select_country_msg': 'Zorg ervoor dat u het land en de stad kiest',
  'text_select_categore_msg': 'Zorg ervoor dat u de categorie kiest',

  'text_all_categories': 'Alle categorieën',
  'text_code_afflet': 'Marketeer code',
  'message': 'Bericht',
  'message_warring_select_country_splash': 'moet worden geselecteerd',
  'big-text1': 'voer e-mail in',
  'big-text2': 'Voer de code in!',
  'big-text3': 'voer een nieuw wachtwoord in',
  'again': 'De e-mail wijzigen?',
  'number': 'Nationaal identiteitsnummer',
  'number_error': 'Het moeten 14 nummers zijn.',
  'face login': 'Inloggen met Facebook',
  'google login': 'Inloggen met Google',
  'are you': 'Ben je dat?',
  'new account': 'Nieuw account',
  'language': 'Taal',
  'birth': 'Geboortedatum',
  'cont': 'Blijven',
  'sagel': 'Aanmelden',
  'pass': 'Wachtwoord',
  'enter-pass': 'wachtwoord invoeren',
  'new pass': 'nieuw wachtwoord',
  're-pass': 'wachtwoord opnieuw invoeren',
  'phone': 'Telefoon',
  'change': 'Wijzigen',
  'online': 'online',
  'offline': 'off line',
  'pass_error': 'Het wachtwoord moet meer dan 8 tekens bevatten',
  'change-mail': 'wijzigen-e-mail',
  'online-payment': 'online betaling',
  'offline-payment': 'offline-betaling',
  'how': 'Hoe',
  'bank': 'bank',
  'kash': 'cash',
  'forgot_password?': 'Wachtwoord vergeten?',
  'please_wait': 'Een ogenblik geduld..',
  'ok': 'Oke',
  'email_error': 'Een geldige e-mail invoeren ',
  'details_error': 'De details mogen niet leeg zijn.',
  'code_error': 'De code moet meer dan 6 cijfers zijn.',
  'pay1': 'Kies uw betalingsplan.',
  'pay2': 'Kies het juiste pakket voor uw maandelijkse werk',
  'plan2': 'Kies dit abonnement',
  'do2': 'Aantal schuifregelaars ',
  'do3': 'Aantal banners',
  'my-plan1': 'Plannen',
  'e': 'er is iets misgegaan, probeer het opnieuw',
  'Loading': 'Laden',
  'text_pass_not_similer':  'Het wachtwoord komt niet overeen',
  'text_p_select_photo':  'Kies een afbeelding en probeer het opnieuw.',
  'side_language_country':  'Taal en land wijzigen',
  'bt_change': 'Wijzigen',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'website',
  'other': 'Andere',
  'promo_code': 'Kortingscode ',
  'promo_code_used': 'Gebruikte kortingscode ',
  'promo_code_accept': 'De kortingscode is intact. ',
  'sub_total': 'Totale kosten',
  'discount': 'Korting',
  'price': 'Totale kosten',
  'Saturday':'Zaterdag',
  'Sunday':'Zondag',
  'Monday':'Maandag',
  'Tuesday':'Dinsdag',
  'Wednesday':'Woensdag',
  'Thursday':'Donderdag',
  'Friday':'Vrijdag',
  'to':'Aan',

  'my-plan2': 'Dit plan wijzigen',
  'my-plan3': 'Geselecteerd pakket voor uw maandelijkse bedrijf',
  'eshtrak': 'Opnieuw abonneren',
  'tagdeed': 'Vernieuwd',
  'bank1': 'Informatie die geschikt is voor bankoverschrijving',
  'bank2': 'Informatie die nodig is voor de bankrekening',
  'bank_info_1': 'Banknaam',
  'bank_info_2': 'rekeningnummer',
  'bank_info_3': 'De naam van de accounteigenaar',
  'bank_info_4': 'Filiaalnaam',
  'bank_info_5': 'Snelle code'
};
