// ignore: always_specify_types
const Map<String, String> en = {

  'read': 'read',
  'active_code': 'active',
  'enter': 'enter',
  'enter_rate':'please enter rate',
  'Male': 'Male',
  'Female': 'Female',
  'text_online-payment': 'choose the appropriate method of online payment',
  'quit_app': 'Are you sure you want to quit ?',
  'Exit': 'Exit' ,
  'Download': 'Download',


  'text_select_time_msg':'make sure to choose time',

  'select_time':'Select Time',
  'show_photo':'Show Photo',


  'select_country': 'Select Country',
  'select_company': 'Select Company',
  'p_choose_country': 'Please choose the country you live in',
  'p_choose_company': 'Which company that wants to renew its subscription',
  'select_language': 'Select Language',
  'bt_done': 'Done',
  'login': 'Login',
  'search': 'Search',
  'search_error': 'Please enter a word for search.',
  'no_data': 'There is currently no data',
  'read_more': 'Read more',
  'read_less': 'Read less',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'Are you?',
  'new_user': 'New User',
  'Marketer': 'Marketer',
  'dealer': 'A company',
  'question_login': 'Already have an account?',
  'new_account': 'New Account',
  'personal_info': 'Personal Info',
  'account_details': 'Account Details',
  'profile_photo': 'Profile Photo',
  'Company_photo': 'Company Photo',
  'text_full_name': 'Full Name',
  'text_full_name_error': 'The e-mail must be entered.',
  'hint_name': 'murafiq',
  'text_country': 'Country',
  'text_defalut_languages': 'Default Languages',
  'text_resturant': 'Company',
  'text_select_Pdf': 'Select Pdf',
  'text_df_language': 'Default Language',
  'text_gender': 'Gender',
  'text_birthDate': 'Date of Birth',
  'text_national_id': 'National ID number / Residency number',
  'text_email': 'Email',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'Password',
  'text_confirm_pass': 'Re-Enter Password',
  'text_phone': 'Phone',
  'text_days': 'Days',
  'text_go': 'Go to',
  'text_phone_error': 'This phone isn\'t right',
  'bt_continue': 'Continue',
  'bt_submit': 'Submit',
  'text_place_name': 'Company Name',
  'text_place_name_error': 'Enter the company name.',
  'text_description': 'Description',
  'text_description_error': 'Enter the description',
  'text_address': 'Address',
  'text_add_address': 'Add Address',
  'text_address_error': 'Enter an address',
  'text_phone2': 'Another mobile number.',
  'text_Tel': 'Telephone',
  'text_fax': 'Fax',
  'text_fax_error': 'The fax number is incorrect.',
  'you_must_login_to_access': 'Please sign in. ',
  'you_must_sub': 'You must subscription ',
  'company_photo': 'Company Photo',
  'text_workdays': 'Work days',
  'text_time_of_work': 'Working hours',
  'text_category': 'Category',
  'select_city': 'Select City',
  'select_category': 'Select Category',
  'select_sub_category': 'Select Sub Category',
  'side_eshtrakaty': 'Subscriptions',
  'side_ads': 'Special Ads',
  'side_search_store': 'Search history',
  'side_notifications': 'Notifications',
  'side_edit_profile': 'Edit Profile',
  'side_edit_company': 'Edit Company',
  'side_mybranches': 'My Branches',
  'side_ask': 'Technical support',
  'side_social': 'Social Links',
  'side_policy': 'Terms and provisions',
  'side_total_client': ' Clients',
  'side_who_us': 'About US',
  'side_logout': 'Logout',
  'side_customers': 'customers',
  'title_resturant': 'Resturant',
  'text_open_Now': 'Open now',
  'text_close': 'Close now',
  'text_special_mark': 'Reviews',
  'text_special_mark_error': 'Enter your review',
  'text_reviews': 'Reviews',
  'bt_leave_review': 'Leave your Review',
  'bt_leave_review_error': 'enter your comment',
  'bt_leave_report': 'Leave your problem.',
  'bt_leave_report_error': 'Enter your problem.',
  'text_done_report': 'The problem was successfully sent.',
  'text_see_more': 'See More',
  'text_more': 'More',
  'text_done_review': 'Your review has been successfully registered',
  'text_under_reiew': 'Your rating is under review',
  'text_your_plan': 'Your Plan',
  'text_your_plan_select': 'A plan has been set for your business.',
  'bt_change_plan': 'Change this plan',
  'bt_change_photo': 'Change photo',
  'bt_profile_photo': 'profile photo',
  'bt_add': 'Add',
  'bt_cancel': 'Cancel',
  'bt_check_out': 'Confirm request',
  'bt_edit': 'Update',
  'bt_edit_bran': 'Edit',
  'text_technical_support': 'Technical Support',
  'text_add_branch': 'Add Branch',
  'text_add_ticket': 'Add Ticket',
  'text_add_social': 'Add a communication site',
  'text_social': 'communication site',
  'hint_link': 'Link',
  'link_error': 'This link is incorrect.',
  'hint_subject': 'Subject',
  'hint_subject_error': 'enter a subject',
  'hint_details': 'Details',
  'hint_details_error': 'Enter details',
  'bt_send': 'Send',
  'hint_your_problem': 'Add your problem here',
  'text_forget_pass': 'Forget Password?',
  'text_set_email': 'Add your email',
  'text_enter_code': 'Please Enter the Code!',
  'text_change_email': 'change this email?',
  'text_code': 'Code',
  'hint_code': 'must be 6 number',
  'bt_sure': 'Confirmation',
  'text_enter_new_pass': 'Please Enter New Password',
  'text_new_pass': 'New Password',
  'text_success_change_pass': 'Your password has been changed successfully ',
  'side_be_delegate': 'Be marketer',
  'side_be_company': 'Be Company',
  'side_be_affilator': 'Be marketer',
  'side_be_delegat': 'Be Company',
  'side_contactus': 'Contact US',
  'bt_add_plan': 'Add your plan',
  'bt_be_delegat': 'Be a marketer.',
  'text_choose-payment': 'Choose the appropriate method of payment',
  'text_offline-payment': '  Choose the appropriate method of Offline payment',
  'text_last_company': 'Recently added',
  'text_review': 'Comments',
  'text_document': 'Document of Company',
  'text_select_country_msg': 'Make sure you choose the country and the city.',
  'text_select_categore_msg': 'Make sure to choose the category',

  'text_all_categories': 'All Categories',
  'text_code_afflet': 'Marketer Code',
  'message': 'Message',
  'message_warring_select_country_splash': 'must be selected',
  'big-text1': 'please enter Email',
  'big-text2': 'please enter the code!',
  'big-text3': 'Please enter a new password',
  'again': 'Change the email?',
  'number': 'National ID number',
  'number_error': 'must be 14 numbers',
  'face login': 'Log in with Facebook',
  'google login': 'Log in with Google',
  'are you': 'Are you ?',
  'new account': 'New Account',
  'language': 'Language',
  'birth': 'Date of Birth',
  'cont': 'continue',
  'sagel': 'login',
  'pass': 'password',
  'enter-pass': 'Password',
  'new pass': 'new password',
  're-pass': 're enter-password',
  'phone': 'phone',
  'change': 'change',
  'online': 'online',
  'offline': 'offline',
  'pass_error': 'the password must be more than 8 characters',
  'change-mail': 'change-mail',
  'online-payment': 'online-payment',
  'offline-payment': 'offline-payment',
  'how': 'how',
  'bank': 'bank',
  'kash': 'cash',
  'forgot_password?': 'Forgot Password?',
  'please_wait': 'please wait..',
  'ok': 'OK',
  'email_error': 'Enter a valid email ',
  'details_error': 'The details shouldn\'t be empty.',
  'code_error': 'the code must be more than 6 numbers',
  'pay1': 'Choose your payment plan',
  'pay2': 'Choose the appropriate package for your monthly work',
  'plan2': 'Choose this plan',
  'do2': 'Number of Sliders ',
  'do3': 'Number of Banners',
  'my-plan1': 'Your Plan',
  'e': 'Something went wrong please try again ',
  'Loading': 'Loading',
  'text_pass_not_similer':  'The PIN is not the same.',
  'text_p_select_photo':  'Choose an image then try again',
  'side_language_country':  'Language & Country',
  'bt_change': 'Change',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'website',
  'other': 'other',
  'promo_code': 'promo Code',
  'promo_code_used': 'promocode used ',
  'promo_code_accept': 'accept promocode ',
  'sub_total': 'sub total',
  'discount': 'Discount',
  'price': 'Total Price',
  'Saturday':'Saturday',
  'Sunday':'Sunday',
  'Monday':'Monday',
  'Tuesday':'Tuesday',
  'Wednesday':'Wednesday',
  'Thursday':'Thursday',
  'Friday':'Friday',
  'to':'to',

  'my-plan2': 'Change This Plan',
  'my-plan3': 'The selected package for your monthly business',
  'eshtrak': 'Re-subscribed',
  'tagdeed': 'Renewed',
  'bank1': 'Appropriate information for bank transfer',
  'bank2': 'Information needed for the bank account',
  'bank_info_1': 'Bank name',
  'bank_info_2': 'account number',
  'bank_info_3': 'The name of the account owner',
  'bank_info_4': 'branch name',
  'bank_info_5': 'Swift Code'


};
