// ignore: always_specify_types
const Map<String, String> es = {
  'Download': 'descargar',
  'read': 'leer',
  'active_code': 'activo',
  'enter': 'entrar',
  'enter_rate': 'por favor ingrese la tarifa',
  'Male': 'masculino',
  'Female': 'hembra',
  'text_online-payment': 'elegir el método adecuado de pago en línea',
  'quit_app': '¿Está seguro de que desea dejar de fumar?',
  'Exit': 'salida',


  'select_country': 'Elegir un país',
  'select_company': 'Elija una empresa',
  'p_choose_country': 'Por favor, elija el país en el que vive..',
  'p_choose_company': '¿Qué empresa le gustaría renovar?',
  'select_language': 'Elija un idioma',
  'bt_done': 'Fue',
  'login': 'Sesión',
  'search': 'Búsqueda',
  'search_error': 'Por favor, introduzca una palabra de búsqueda.',
  'no_data': 'Actualmente no hay datos',
  'read_more': 'Leer más',
  'text_more': ' Más',
  'read_less': 'Lee menos.',
  'al_murafiq': 'Al_Murafiq',
  'are_you': '¿estas?',
  'new_user': 'Nuevo usuario',
  'Marketer': 'Comercializador',
  'dealer': 'Una empresa',
  'question_login': '¿Tienes una cuenta?',
  'new_account': 'Nueva cuenta',
  'personal_info': 'Información personal',
  'account_details': 'Detalles de la cuenta',
  'profile_photo': 'Un selfie.',
  'Company_photo': 'Empresa de logotipos',
  'text_full_name': 'Nombre completo',
  'text_full_name_error': 'Tienes que conseguir el e-mail.',
  'hint_name': 'murafiq',
  'text_country': 'El apoyo del gobierno',
  'text_defalut_languages': 'Idioma predeterminado',
  'text_resturant': 'Empresa',
  'text_select_Pdf': 'Añadir un archivo',
  'text_df_language': 'Idioma predeterminado',
  'text_gender': 'Tipo',
  'text_birthDate': 'Fecha de nacimiento',
  'text_national_id': 'Identificación.',
  'text_email': 'Correo electrónico',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'El número secreto.',
  'text_confirm_pass': 'Confirme el número pin',
  'text_phone': 'Número de teléfono',
  'text_days': 'Días',
  'text_go': 'Vete a',
  'text_phone_error': 'Este móvil no está bien.',
  'bt_continue': 'Sigue.',
  'bt_submit': 'Añadir',
  'text_place_name': 'El nombre de la compañía.',
  'text_place_name_error': ' Introduzca el nombre de la empresa.',
  'text_description': 'Detalles',
  'text_description_error': 'Introduzca los detalles',
  'text_address': 'Dirección',
  'text_add_address': 'Añadir el título',
  'text_address_error': 'Introduzca la dirección',
  'text_phone2': 'Otro número de móvil.',
  'text_Tel': 'Tierra No.',
  'text_fax': 'Número de fax',
  'text_fax_error': 'El número de fax es incorrecto.',
  'you_must_login_to_access': 'Por favor, inicia sesión.',
  'you_must_sub': 'Debe suscripciones ',
  'company_photo': 'Foto de la empresa',
  'text_workdays': 'Días laborables',
  'text_time_of_work': 'Horario de trabajo',
  'text_category': 'Categorías',
  'select_city': 'seleccionar la ciudad',
  'select_category': 'seleccionar la categoría',
  'select_sub_category': 'Elija una clasificación de sucursal',
  'side_eshtrakaty': 'Contribuciones',
  'side_ads': 'Anuncios premium',
  'side_search_store': 'Historial de búsqueda',
  'side_edit_profile': 'Ajuste la cuenta',
  'side_edit_company': 'Modificación de la empresa',
  'side_mybranches': 'Mis ramas.',
  'side_ask': 'Soporte técnico',
  'side_social': 'vínculo social',
  'side_policy': 'Términos y disposiciones',
  'side_total_client': 'Cliente',
  'side_notifications': 'Avisos',
  'side_who_us': '¿Quiénes somos',
  'side_logout': 'Registrado',
  'side_customers': 'Clientes',
  'title_resturant': 'Restaurante',
  'text_open_Now': 'Abrir ahora',
  'text_close': 'Ya está cerrado.',
  'text_special_mark': 'Comentarios',
  'text_special_mark_error': 'Introduzca sus notas',
  'text_reviews': 'Comentarios',
  'bt_leave_review': 'Dejo un comentario.',
  'bt_leave_review_error': 'Introduzca su comentario',
  'bt_leave_report': 'Deja tu problema.',
  'bt_leave_report_error': 'Entra en tu problema.',
  'text_done_report': 'El problema se envió correctamente.',
  'text_see_more': 'Leer más',
  'text_done_review': 'Su opinión ha sido grabada con éxito',
  'text_under_reiew': 'Su opinión editada.',
  'text_your_plan': 'Planes',
  'text_your_plan_select': 'Se ha establecido un plan para su negocio.',
  'bt_change_plan': 'Cambiar el plan',
  'bt_change_photo': 'Zhang Foto',
  'bt_profile_photo': 'Foto de perfil',
  'bt_add': 'Añadir',
  'bt_cancel': 'Cancelar',
  'bt_check_out': 'Confirmar la solicitud',
  'bt_edit': 'Modificar',
  'bt_edit_bran': 'Modificar',
  'text_technical_support': 'Soporte técnico',
  'text_add_branch': 'Añadir una rama',
  'text_add_ticket': 'Agregue un boleto.',
  'text_add_social': 'Agregar un sitio de comunicación',
  'text_social': 'Sitio de redes',
  'hint_link': 'Enlace',
  'link_error': 'Este enlace es incorrecto.',
  'hint_subject': 'Asunto',
  'hint_subject_error': 'Introduzca el asunto.',
  'hint_details': 'Detalles',
  'hint_details_error': 'Introduzca los detalles',
  'bt_send': 'Enviar',
  'hint_your_problem': 'Agregue su problema aquí',
  'text_forget_pass': '¿Olvidaste la contraseña?',
  'text_set_email': 'Añade tu correo electrónico',
  'text_enter_code': 'Por favor, introduzca el código!',
  'text_change_email': '¿Cambiar el e-mail?',
  'text_code': 'Icono',
  'hint_code': 'Tiene que ser de seis dígitos.',
  'bt_sure': 'Confirmación',
  'text_enter_new_pass': 'Introduzca la nueva contraseña.',
  'text_new_pass': 'Nueva contraseña',
  'text_success_change_pass': 'La contraseña se ha cambiado correctamente. ',
  'side_be_delegate': 'Sé un vendedor.',
  'side_be_company': 'Sé un vendedor.',
  'side_be_affilator': 'Ser una empresa',
  'side_be_delegat': 'Sé un vendedor',
  'side_contactus': 'En contacto con nosotros',
  'bt_add_plan': 'Añadir plan',
  'bt_be_delegat': 'Sé un vendedor',
  'text_choose-payment': 'Elija el método de pago adecuado',
  'text_offline-payment': '  Chus El Apropriat Doron de Oflin Bayment',
  'text_last_company': 'Últimas empresas',
  'text_review': 'Comentarios',
  'text_document': 'Documento de la empresa',
  'text_select_country_msg': 'Asegúrese de elegir el país y la ciudad',
  'text_select_categore_msg': 'Asegúrese de elegir el elemento',

  'text_all_categories': 'Todas las calificaciones',
  'text_code_afflet': 'Código de comercializador',
  'message': 'Mensajes',
  'message_warring_select_country_splash': 'debe seleccionarse',
  'big-text1': 'Por favor, recibe el e-mail.',
  'big-text2': 'Por favor, introduzca el código!',
  'big-text3': 'por favor, introduzca \n una nueva contraseña',
  'again': '¿Cambiar el correo electrónico?',
  'number': 'Número de identidad nacional',
  'number_error': 'Tiene que ser 14 números.',
  'face login': 'Inicia sesión con Facebook',
  'google login': 'Inicia sesión a través de Google',
  'are you': '¿estas?',
  'new account': 'Nueva cuenta',
  'language': 'Idioma',
  'birth': 'Fecha de nacimiento',
  'cont': 'Continuar',
  'sagel': 'Fecha de nacimiento',
  'pass': 'Sigue.',
  'enter-pass': 'Contraseña',
  'new pass': 'nueva contraseña',
  're-pass': 'Confirme el PIN',
  'phone': 'Teléfono',
  'change': 'cambio',
  'online': 'en línea',
  'offline': 'sin conexión',
  'pass_error': 'La contraseña debe tener más de 8 caracteres',
  'change-mail': 'cambiar el correo',
  'online-payment': 'pago en línea',
  'offline-payment': 'pago fuera de línea',
  'how': 'Cómo',
  'bank': 'Banco',
  'kash': 'Efectivo',
  'forgot_password?': '¿Olvidaste la contraseña?',
  'please_wait': 'Espera..',
  'ok': 'Bien',
  'email_error': 'Introduzca un correo electrónico disponible  ',
  'details_error': 'Los detalles no deberían estar vacíos.  ',
  'code_error': 'El código debe tener más de 6 dígitos.',
  'pay1': 'Elija el plan de pago.',
  'pay2': 'Elija el paquete adecuado para su trabajo mensual',
  'plan2': 'Elija este plan.',
  'do2': 'Número de slider ',
  'do3': 'Número de banners',
  'my-plan1': 'Su plan',
  'e': 'algo salió mal intentarlo de nuevo más tarde',
  'Loading': 'Carga',
  'text_pass_not_similer':  'El PIN no es el mismo.',
  'text_p_select_photo':  'Elige una foto e inténtalo de nuevo.',
  'side_language_country':  'Cambio de idioma & País',
  'bt_change': 'cambio',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'Sitio web',
  'other': 'Otro',
  'promo_code': 'Código de descuento',
  'promo_code_used': 'Código de descuento utilizado',
  'promo_code_accept': 'El código de descuento está intacto. ',
  'sub_total': 'La capacidad del gobierno',
  'discount': 'Descuento',
  'price': 'Precio total',
  'Saturday':'Sábado',
  'Sunday':'Domingo',
  'Monday':'Lunes',
  'Tuesday':'Martes',
  'Wednesday':'Miércoles',
  'Thursday':'Jueves',
  'Friday':'Viernes',
  'to':'Para',

  'my-plan2': 'Este plan está cambiando.',
  'my-plan3': 'El paquete seleccionado para su negocio mensual',
  'eshtrak': 'Volver a suscribirse',
  'tagdeed': 'Renovado',
  'bank1': 'Información requerida para la cuenta bancaria',
  'bank2': 'Información requerida para la cuenta bancaria',
  'bank_info_1': 'Nombre del banco',
  'bank_info_2': 'número de cuenta',
  'bank_info_3': 'El nombre del propietario de la cuenta',
  'bank_info_4': ' nombre de la rama',
  'bank_info_5': 'Código Swift',


  'text_select_time_msg':'Asegúrese de elegir la hora',
  'select_time':'Límite de tiempo',
  'show_photo':'Mostrar la imagen'
};
