// ignore: always_specify_types
const Map<String, String> fr = {
  'Download': 'télécharger',
  'read':'lire',
  'active_code': 'actif',
  'enter': 'entrer',
  'enter_rate':'s’il vous plaît entrer le taux',
  'Male': 'mâle',
  'Female': 'femelle',
  'text_online-payment': 'choisir le mode de paiement en ligne approprié',
  'quit_app': 'Etes-vous sûr que vous voulez arrêter ?',
  'Exit': 'sortie',



  'select_country': 'Choisissez un pays',
  'select_company': 'Choisissez une entreprise',
  'p_choose_country': 'S’il vous plaît choisir le pays où vous vivez.',
  'p_choose_company': 'Quelle entreprise souhaitez-vous renouveler?',
  'select_language': 'choisir la langue',
  'bt_done': 'Fait',
  'login': 'connectez-vous',
  'search': 'rechercher',
  'search_error': 'S’il vous plaît entrer un mot de recherche.',
  'no_data': 'Il n’existe actuellement aucune donnée',
  'read_more': 'Lire la suite',
  'text_more': 'Plus',
  'read_less': 'Lire moins',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'Êtes-vous?',
  'new_user': 'Nouvel utilisateur',
  'Marketer': 'Commercialisation',
  'dealer': 'Une entreprise',
  'question_login': 'Avez-vous un compte?',
  'new_account': 'Nouveau compte',
  'personal_info': 'Renseignements personnels',
  'account_details': 'Détails du compte',
  'profile_photo': 'Selfie ',
  'Company_photo': 'Société Logo',
  'text_full_name': 'Nom complet',
  'text_full_name_error': 'Vous devez obtenir l’e-mail.',
  'hint_name': 'murafiq',
  'text_country': 'L’appui du gouvernement',
  'text_defalut_languages': 'Langue par défaut',
  'text_resturant': 'Société',
  'text_select_Pdf': 'Ajouter un fichier',
  'text_df_language': 'Langue par défaut',
  'text_gender': 'Type',
  'text_birthDate': 'Date de naissance',
  'text_national_id': 'Numéro d’identification',
  'text_email': 'Messagerie électronique',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'Le numéro secret.',
  'text_confirm_pass': 'Confirmation du numéro secret',
  'text_phone': 'Numéro de téléphone',
  'text_days': 'Jours',
  'text_go': 'Atteindre',
  'text_phone_error': 'Ce mobile n’est pas juste.',
  'bt_continue': 'Complet',
  'bt_submit': 'Ajouter',
  'text_place_name': 'Le nom de l’entreprise.',
  'text_place_name_error': 'Entrez le nom de l’entreprise',
  'text_description': 'Détails',
  'text_description_error': 'Entrez les détails.',
  'text_address': 'Adresse',
  'text_add_address': 'Ajouter une adresse',
  'text_address_error': 'Entrez une adresse',
  'text_phone2': 'Un autre numéro de portable.',
  'text_Tel': 'Terre No.',
  'text_fax': 'Numéro de fax',
  'text_fax_error': 'Le numéro de fax est incorrect.',
  'you_must_login_to_access': ' S’ll vous plaît, connectez-vous.',
  'you_must_sub': ' Vous devez vous abonner',
  'company_photo': ' Photo d’entreprise',
  'text_workdays': 'Jours ouvrables',
  'text_time_of_work': 'Heures de travail',
  'text_category': 'Catégories',
  'select_city': 'Sélectionnez Ville',
  'select_category': 'Choisissez une note',
  'select_sub_category': 'Choisissez une sous-évaluation',
  'side_eshtrakaty': 'Contributions',
  'side_ads': 'Annonces premium',
  'side_search_store': 'Historique de recherche',
  'side_edit_profile': 'Ajuster le compte',
  'side_social': 'Liens sociaux',
  'side_edit_company': 'Modification de l’entreprise',
  'side_notifications': 'Avis',
  'side_mybranches': 'Mes branches.',
  'side_ask': 'Support technique',
  'side_policy': 'Modalités et dispositions',
  'side_total_client': 'Client',
  'side_who_us': 'Qui sommes-nous',
  'side_logout': 'Connecté',
  'side_customers': 'Les clients',
  'title_resturant': 'Restaurant',
  'text_open_Now': 'Ouvrez maintenant.',
  'text_close': 'C’est fermé maintenant.',
  'text_special_mark': 'critiques',
  'text_special_mark_error': 'Entrez vos notes',
  'text_reviews': 'Pour les commentaires',
  'bt_leave_review': 'Laisser un commentaire',
  'bt_leave_review_error': 'Entrez votre commentaire',
  'bt_leave_report': 'Laisse ton problème.',
  'bt_leave_report_error': 'Entrez votre problème.',
  'text_done_report': 'Le problème a été envoyé avec succès.',
  'text_see_more': 'Lire la suite',
  'text_done_review': 'Votre opinion a été enregistrée avec succès',
  'text_under_reiew': 'Votre avis a été modifié.',
  'text_your_plan': 'plans',
  'text_your_plan_select': 'Un plan a été établi pour votre entreprise.',
  'bt_change_plan': 'Modifier le paquet',
  'bt_change_photo': 'Changer l’image',
  'bt_profile_photo': 'Le selfie.',
  'bt_add': 'Ajouter',
  'bt_cancel': 'Annuler',
  'bt_check_out': 'Confirmer la demande',
  'bt_edit': 'Modifier',
  'bt_edit_bran': 'Modifier',
  'text_technical_support': 'Support technique',
  'text_add_branch': 'Ajouter une branche',
  'text_add_ticket': 'Ajoutez un billet.',
  'text_add_social': 'Ajouter un site de réseautage',
  'text_social': ' Un site réseau',
  'hint_link': 'Lien',
  'link_error': 'erreur de lien',
  'hint_subject': 'Objet',
  'hint_subject_error': 'Entrez le sujet.',
  'hint_details': 'Détails',
  'hint_details_error': 'Entrez les détails',
  'bt_send': 'Envoyer',
  'hint_your_problem': 'Ajoutez votre problème ici.',
  'text_forget_pass': 'Tu as oublié le mot de passe ?',
  'text_set_email': 'Ajoutez votre e-mail',
  'text_enter_code': 'S’il vous plaît entrer le code!',
  'text_change_email': 'Changer l’e-mail?',
  'text_code': 'Icône',
  'hint_code': 'Ça doit être six chiffres.',
  'bt_sure': 'Confirmation',
  'text_enter_new_pass': 'S’il vous plaît entrer mon nouveau mot de passe.',
  'text_new_pass': 'Nouveau mot de passess',
  'text_success_change_pass': ' Le mot de passe a été modifié avec succès.',
  'side_be_delegate': 'Sois un spécialiste du marché.',
  'side_be_company': 'Être une entreprise',
  'side_be_affilator': 'Sois un spécialiste du marché.',
  'side_be_delegat': 'Être une entreprise',
  'side_contactus': 'Entrez en contact avec nous',
  'bt_add_plan': 'Ajoutez votre plan.',
  'bt_be_delegat': 'Sois un spécialiste du marché.',
  'text_choose-payment': 'Choisissez le bon mode de paiement',
  'text_offline-payment': ' Choisissez le mode de paiement hors ligne approprié ',
  'text_last_company': 'Récemment ajouté',
  'text_review': 'Commentaires',
  'text_document': 'Document de société',
  'text_select_country_msg': 'Assurez-vous de choisir l’État et la ville',
  'text_select_categore_msg': 'Assurez-vous de choisir l’article',

  'text_all_categories': 'Toutes les cotes d’écoute',
  'text_code_afflet': 'Code marketeur',
  'message': 'Message',
  'message_warring_select_country_splash': 'doivent être sélectionnés',
  'big-text1': 'S’il vous plaît obtenir l’e-mail.',
  'big-text2': 'S’il vous plaît entrer le code!',
  'big-text3': 'Entrez le nouveau NIP, s’il vous plaît.',
  'again': 'Changer d’e-mail ?',
  'number': 'Numéro d’identité nationale ',
  'number_error': 'Ça doit être 14 chiffres.',
  'face login': 'Connectez-vous avec Facebook',
  'google login': 'Connectez-vous via Google',
  'are you': 'Êtes-vous?',
  'new account': 'Un nouveau compte ?',
  'language': 'Langue',
  'birth': 'Date de naissance',
  'cont': 'Allez',
  'sagel': 'connectez-vous',
  'pass': 'connectez-vous',
  'enter-pass': 'mot de passe',
  'new pass': 'nouveau mot de passe',

  're-pass': 'Confirmer le NIP',
  'phone': 'Téléphone',
  'change': 'changement',
  'online': 'online',
  'offline': 'hors-ligne',
  'pass_error': 'Le mot de passe doit être de plus de 8 caractères',
  'change-mail': 'Changer le courrier',
  'online-payment': 'paiement en lignet',
  'offline-payment': 'paiement hors ligne',
  'how': 'Comment',
  'bank': 'Banque',
  'kash': 'Argent',
  'forgot_password?': 'Avez-vous oublié le mot de passe?',
  'please_wait': ' J’attends, s’il vous plaît.',
  'ok': 'd\'accord',
  'email_error': 'Entrez un e-mail disponible ',
  'details_error': 'Les détails ne devraient pas être vides. ',
  'code_error': 'Le code doit être supérieur à 6 chiffres.',
  'pay1': 'Choisissez votre plan de paiement.',
  'pay2': 'Choisissez le bon moment pour votre entreprise mensuelle',
  'plan2': 'Choisissez ce plan.',
  'do2': 'nombre de curseurs ',
  'do3': 'nombre de bannières',
  'my-plan1': ' Plan',
  'e': 'Something went wrong and tried again',
  'Loading': 'Chargement',
  'text_pass_not_similer':  'Le NIP n’est pas le même.',
  'text_p_select_photo':  'Choisissez une image et réessayer',
  'side_language_country':  'Changer la langue et le pays',
  'bt_change': 'changement',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'site internet',
  'other': 'Autres',
  'promo_code': 'Code d’escompte',
  'promo_code_used': 'Code d’escompte utilisateur',
  'promo_code_accept': 'Le code de réduction est intact.',
  'sub_total': 'sous-total',
  'discount': 'Réductiont',
  'price': 'Coût total',
  'Saturday':'Samedi',
  'Sunday':'Dimanche',
  'Monday':'Lundi',
  'Tuesday':'Tuesday',
  'Wednesday':'Mercredi',
  'Thursday':'Jeudi',
  'Friday':'Vendredi',
  'to':'À',

  'my-plan2': 'Modifier ce plan',
  'my-plan3': 'Le forfait sélectionné pour votre activité mensuelle',
  'eshtrak': 'Ré-abonnez-vous',
  'tagdeed': 'Renouvelé',
  'bank1': 'Informations requises pour le compte bancaire',
  'bank2': 'Informations requises pour le compte bancaire',
  'bank_info_1': 'Nom de la banque',
  'bank_info_2': 'numéro de compte',
  'bank_info_3': 'Le nom du propriétaire du compte',
  'bank_info_4': 'nom de branche',
  'bank_info_5': 'Swift Code',

  'text_select_time_msg':'Assurez-vous de choisir l’heure',
  'select_time':'Limite de temps',
  'show_photo':'Afficher l’image'
};
