// ignore: always_specify_types
const Map<String, String> hi = {


  'Download': 'डाउनलोड',
  'read': 'पढ़ना',
  'active_code': 'सक्रिय',
  'enter': 'दर्ज',
  'enter_rate': 'कृपया दर दर्ज करें',
  'Male': 'पुरुष',
  'Female': 'महिला',
  'text_online-payment': 'ऑनलाइन भुगतान की उपयुक्त विधि चुनें',
  'quit_app': 'क्या आप सुनिश्चित हैं कि आप पद छोड़ना चाहते हैं?',
  'Exit': 'निकासी',


  'select_country': 'एक देश चुनें',
  'select_company': 'एक कंपनी चुनें',
  'p_choose_country': 'कृपया उस देश को चुनें जिसमें आप रहते हैं।',
  'p_choose_company': 'आप किस कंपनी को नवीनीकृत करना चाहेंगे?',
  'select_language': 'एक भाषा चुनें',
  'bt_done': 'था',
  'login': 'लॉगऑन',
  'search': 'खोज',
  'search_error': 'कृपया एक खोज शब्द दर्ज करें।',
  'no_data': 'वर्तमान में कोई डेटा नहीं है',
  'read_more': 'और पढ़ें',
  'text_more': ' अधिक',
  'read_less': 'कम पढ़ें',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'क्या आप?',
  'new_user': 'नया उपयोगकर्ता',
  'Marketer': 'विपणन',
  'dealer': 'एक कंपनी',
  'question_login': 'क्या आपके पास कोई खाता है?',
  'new_account': 'नया खाता',
  'personal_info': 'व्यक्तिगत जानकारी',
  'account_details': 'खाते का विवरण',
  'profile_photo': 'सेल्फी',
  'Company_photo': 'लोगो कंपनी',
  'text_full_name': 'पूरा नाम',
  'text_full_name_error': 'इसके लिए आपको ई-मेल करवाना होगा।',
  'hint_name': 'murafiq',
  'text_country': 'सरकार का समर्थन',
  'text_defalut_languages': 'डिफ़ॉल्ट भाषा',
  'text_resturant': 'अतिथि',
  'text_select_Pdf': 'फाइल जोड़ें',
  'text_df_language': 'डिफ़ॉल्ट भाषा',
  'text_gender': 'प्रकार',
  'text_birthDate': 'जन्म तिथि',
  'text_national_id': 'आईडी नंबर',
  'text_email': 'ई मेल',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'पिन',
  'text_confirm_pass': 'पासवर्ड फिर से दर्ज करें',
  'text_phone': 'फोन संख्या',
  'text_days': 'दिन',
  'text_go': 'यहाँ जाओ',
  'text_phone_error': 'यह मोबाइल सही नहीं है।',
  'bt_continue': 'जारी रखना',
  'bt_submit': 'आगे बढ़ो।',
  'text_place_name': 'कंपनी का नाम',
  'text_place_name_error': 'कंपनी का नाम दर्ज करें',
  'text_description': 'विवरण',
  'text_description_error': 'विवरण दर्ज करें',
  'text_address': 'पता',
  'text_add_address': 'पता जोड़ना',
  'text_address_error' : 'एक पता दर्ज करें',
  'text_phone2': 'एक और मोबाइल नंबर।',
  'text_Tel': 'भूमि नं.',
  'text_fax': 'फैक्स नंबर',
  'text_fax_error': 'फैक्स नंबर गलत है।',
  'you_must_login_to_access': 'कृपया साइन इन करें। ',
  'you_must_sub': 'आपको सदस्यता देनी होगी ',
  'company_photo': 'कंपनी फोटो',
  'text_workdays': 'कार्य दिवस',
  'text_time_of_work': 'काम के घंटे',
  'text_category': 'श्रेणियाँ',
  'select_city': 'एक शहर चुनें।',
  'select_category': 'रेटिंग चुनें',
  'select_sub_category': 'एक उप-वर्गीकरण चुनें',
  'side_eshtrakaty': 'योगदान',
  'side_ads': 'विशेष विज्ञापन',
  'side_search_store': 'इतिहास खोजें',
  'side_edit_profile': 'खाते को समायोजित करना',
  'side_edit_company': 'कंपनी संशोधन',
  'side_notifications': 'नोटिफिकट्यून्स',
  'side_mybranches': 'मेरी शाखाएं',
  'side_ask': 'समर्थन एक',
  'side_social': 'सामाजिक लिंक',
  'side_policy': 'नियम और प्रावधान',
  'side_total_client': 'कुल ग्राहक',
  'side_who_us': 'हमारे बारे में',
  'side_logout': 'लॉगआउट',
  'side_customers': 'ग्राहकों',
  'title_resturant': 'भोजनालय',
  'text_open_Now': 'अब खुला',
  'text_close': 'बंद करना',
  'text_special_mark': 'समीक्षाएँ',
  'text_special_mark_error': 'अपने नोट्स दर्ज करें',
  'text_reviews': 'टिप्पणियाँ',
  'bt_leave_review': 'अपनी समीक्षा लाइव करें',
  'bt_leave_review_error': 'इंटर योर कॉमनेट',
  'bt_leave_report': 'अपनी रिपोर्ट लाइव करें',
  'bt_leave_report_error': 'इंटर योर रिपोर्ट',
  'text_done_report': 'समस्या को सफलतापूर्वक भेजा गया।',
  'text_see_more': 'अधिक देखें',
  'text_done_review': 'आपकी समीक्षा सफलतापूर्वक पंजीकृत की गई है',
  'text_under_reiew': 'आपकी रेटिंग गैरेज के नीचे है। ...',
  'text_your_plan': 'योर ब्लैंक',
  'text_your_plan_select': 'आपके काम के लिए कोई योजना बनाई गई है।',
  'bt_change_plan': 'इस योजना को बदलें',
  'bt_change_photo': ' फोटो बदलें',
  'bt_profile_photo': 'प्रोफाइल पिक्चर',
  'bt_add': 'आगे कहना',
  'bt_cancel': 'रद्द करना',
  'bt_check_out': 'देखो',
  'bt_edit': 'संशोधित',
  'bt_edit_bran': 'संशोधित',
  'text_technical_support': 'तकनीकी सहायता',
  'text_add_branch': 'एड शाखा',
  'text_add_ticket': 'विज्ञापन टेकट',
  'text_add_social': 'सोशल मीडिया जोड़ना',
  'text_social': ' सोशल मीडिया',
  'hint_link': 'लिंक',
  'link_error': 'यह लिंक गलत है।',
  'hint_subject': 'विषय',
  'hint_subject_error': 'विषय में प्रवेश करना',
  'hint_details': 'विवरण',
  'hint_details_error': 'विवरण दर्ज करें।',
  'bt_send': 'भेजें',
  'hint_your_problem': 'अपनी समस्या यहां जोड़ें ।',
  'text_forget_pass': 'क्या आप पासवर्ड भूल गए?',
  'text_set_email': 'अपना ई-मेल जोड़ें',
  'text_enter_code': 'कृपया कोड दर्ज करें!',
  'text_change_email': 'ई-मेल बदलें?',
  'text_code': 'चिह्न',
  'hint_code': 'इसके लिए छह अंक देने होंगे।',
  'bt_sure': 'पुष्टिकरण',
  'text_enter_new_pass': 'कृपया नया पासवर्ड डालें।',
  'text_new_pass': ' नया पासवर्ड',
  'text_success_change_pass': 'पासवर्ड सफलतापूर्वक बदल दिया गया है ',
  'side_be_delegate': 'केन मासूक़',
  'side_be_company': 'एक कंपनी बन',
  'side_be_affilator': 'केन मासूक़',
  'side_be_delegat': 'एक कंपनी बन',
  'side_contactus': 'हमारे साथ संपर्क में रहें',
  'bt_add_plan': 'अपनी योजना जोड़ें।',
  'bt_be_delegat': 'केन मासूक़',
  'text_choose-payment': 'सही भुगतान विधि चुनें',
  'text_offline-payment': '  ऑफ़लाइन भुगतान की उपयुक्त विधि चुनें',
  'text_last_company': 'हाल ही में जोड़ा गया',
  'text_review': 'टिप्पणियाँ',
  'text_document': 'कंपनी का दस्तावेज',
  'text_select_country_msg': 'सुनिश्चित करें कि आप देश और शहर का चयन करें',
  'text_select_categore_msg': 'सुनिश्चित करें कि आप आइटम चुनते हैं',

  'text_all_categories': 'सभी श्रेणियां',
  'text_code_afflet': 'मार्केटर कोड',
  'message': 'संदेश',
  'message_warring_select_country_splash': 'चयनित किया जाना चाहिए',
  'big-text1': 'कृपया ईमेल दर्ज करें',
  'big-text2': 'कृपया कोड दर्ज करें!',
  'big-text3': 'कृपया एक नया \n पासवर्ड दर्ज करें',
  'again': 'ईमेल बदलें?',
  'number': 'राष्ट्रीय पहचान संख्या',
  'number_error': 'इसके लिए 14 नंबर देने होंगे।',
  'face login': 'फेसबुक के साथ लॉग इन करें',
  'google login': 'गूगल के साथ लॉग इन करें',
  'are you': ' क्या आप?',
  'new account': 'नया खाता',
  'language': 'भाषा',
  'birth': 'जन्म तिथि',
  'cont': 'जारी रखना',
  'sagel': 'लॉगिन',
  'pass': 'सफल होना',
  'enter-pass': 'पासवर्ड',
  'new pass': 'नया पासवर्ड',
  're-pass': 'पिन की पुष्टि करें',
  'phone': 'फ़ोन',
  'change': 'छोटे सिक्‍के',
  'online': 'ऑनलाइन',
  'offline': 'भुगतान के अन्य तरीके',
  'pass_error': 'पासवर्ड 8 से अधिक वर्ण होना चाहिए',
  'change-mail': 'मेल बदलें',
  'online-payment': 'ऑनलाइन भुगतान',
  'offline-payment': 'ऑफ़लाइन भुगतान',
  'how': 'कैसे',
  'bank': 'खाता होना',
  'kash': 'नकद',
  'forgot_password?': 'पासवर्ड भूल गया?',
  'please_wait': 'कृपया प्रतीक्षा करो।।',
  'ok': 'ठीक',
  'email_error': 'एक उपलब्ध ईमेल दर्ज करें  ',
  'details_error': 'विवरण खाली नहीं होना चाहिए ।',
  'code_error': 'कोड 6 अंकों से अधिक होना चाहिए।',
  'pay1': 'अपनी भुगतान योजना चुनें',
  'pay2': 'अपने मासिक काम के लिए उपयुक्त पैकेज चुनें',
  'plan2': 'इस योजना को चुनें',
  'do2': 'स्लाइडर की संख्या ',
  'do3': ' बैनर की संख्या',
  'my-plan1': 'आपकी योजना',
  'e': 'कुछ गलत हो गया कृपया फिर से कोशिश करें',
  'Loading': 'लोड',
  'text_pass_not_similer':  'पिन एक ही नहीं है।',
  'text_p_select_photo':  'एक तस्वीर चुनें और फिर से प्रयास करें।',
  'side_language_country':  'बदलती भाषा और राज्य',
  'bt_change': 'छोटे सिक्‍के',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'वेबसाइट',
  'other': 'अन्य',
  'promo_code': 'डिस्काउंट कोड',
  'promo_code_used': 'डिस्काउंट कोड का इस्तेमाल किया',
  'promo_code_accept': 'डिस्काउंट कोड बरकरार है।',
  'sub_total': 'उप कुल',
  'discount': 'छूट',
  'price': 'कुल कीमत',
  'Saturday':'शानिवार',
  'Sunday':'रविवार',
  'Monday':'सोमवार',
  'Tuesday':'मंगलवार',
  'Wednesday':'बुधवार',
  'Thursday':'गुरूवार',
  'Friday':'शुक्रवार',
  'to':'करने के लिए',

  'my-plan2': 'इस योजना को बदलें',
  'my-plan3': 'आपके मासिक व्यवसाय के लिए चयनित पैकेज',
  'eshtrak': 'फिर से सदस्यता लें',
  'tagdeed': 'नवीनीकृत',
  'bank1': 'बैंक हस्तांतरण के लिए उचित जानकारी',
  'bank2': 'ओंक स्थानांतरण',
  'bank_info_1': 'बैंक का नाम',
  'bank_info_2': 'खाता संख्या',
  'bank_info_3': 'खाताधारक का नाम',
  'bank_info_4': 'शाखा नाम',
  'bank_info_5': 'स्विफ्ट कोड',

  'text_select_time_msg':'सुनिश्चित करें कि आप समय चुनते हैं',
  'select_time':'अंतिम तिथि',
  'show_photo':'छवि दिखाएं'

};
