// ignore: always_specify_types
const Map<String, String> ja = {
  'Download': 'ダウンロード',
  'read':'読む',
  'active_code': '能動',
  'enter':'入る',
  'enter_rate': 'レートを入力してください',
  'Male': '男性',
  'Female': '女性',
  'text_online-payment': '適切なオンライン支払方法を選択する',
  'quit_app': '終了してもよいですか?',
  'Exit': '出口',



  'text_select_time_msg':'時間を選択してください',
  'select_time':'制限時間',
  'show_photo':'画像を表示する',
  'select_country': '国の選択',
  'select_company': '会社の選択',
  'p_choose_country': '住んでいる国を選んでください.',
  'p_choose_company': 'サブスクリプションを更新する会社ا',
  'select_language': '言語の選択',
  'bt_done': '完成です',
  'login': 'ログイン',
  'search': '検索',
  'search_error': '検索が空ではありません',
  'no_data': 'データなし',
  'read_more': '続きを読む',
  'text_more': 'もっとその',
  'read_less': '読むを減らす',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'あなたは。',
  'new_user': '新規ユーザー',
  'Marketer': 'マーケティング 担当者',
  'dealer': '売り手',
  'question_login': 'すでにアカウントを持っていますか?',
  'new_account': '新しいアカウント',
  'personal_info': '個人情報',
  'account_details': 'アカウントの詳細',
  'profile_photo': 'プロフィール写真',
  'Company_photo': 'ロゴ会社',
  'text_full_name': 'フルネーム',
  'text_full_name_error': '名前があります。',
  'hint_name': 'murafiq',
  'text_country': '国',
  'text_defalut_languages': 'デフォルト言語',
  'text_resturant': '会社',
  'text_select_Pdf': 'PDF の選択',
  'text_df_language': 'デフォルト言語',
  'text_gender': '性別',
  'text_birthDate': '生年月日',
  'text_national_id': 'ナショナル・アイデンティティ・ナンバー / レジデンシー番号',
  'text_email': '電子メール',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'パスワード',
  'text_confirm_pass': '秘密番号の確認',
  'text_phone': 'ヴォーナ',
  'text_days': '日',
  'text_go': 'に移動する',
  'text_phone_error': 'このモバイルは正しくありません。',
  'bt_continue': 'コンティーニョ',
  'bt_submit': '追加',
  'text_place_name': '会社名',
  'text_place_name_error': '会社名を入力してください',
  'text_description': '詳細',
  'text_description_error': '詳細を入力します。',
  'text_address': 'アドレス',
  'text_add_address': '住所を追加する',
  'text_address_error': '住所を入力する',
  'text_phone2': '別の携帯電話番号。',
  'text_Tel': '土地No.',
  'text_fax': 'ファックス番号',
  'text_fax_error': 'FAX 番号が正しくありません。',
  'you_must_login_to_access': 'サインインしてください。 ',
  'you_must_sub': 'サインアップする必要があります。 ',
  'company_photo': '会社の写真',
  'text_workdays': '営業日',
  'text_time_of_work': '労働時間',
  'text_category': 'カテゴリ',
  'select_city': '都市を選択します。',
  'select_category': '評価の選択',
  'select_sub_category': 'ブランチの評価を選択する',
  'side_eshtrakaty': '貢献',
  'side_ads': 'プレミアム広告',
  'side_search_store': '検索履歴',
  'side_edit_profile': 'アカウントの調整',
  'side_notifications': 'ノティフィカチューン',
  'side_edit_company': '会社の変更',
  'side_mybranches': '私の枝。',
  'side_ask': 'テクニカルサポート',
  'side_social': 'ソーシャルメディア',
  'side_policy': '利用規約および規定',
  'side_total_client': '顧客',
  'side_who_us': '私たちは誰ですか',
  'side_logout': '記録',
  'side_customers': 'クライアント',
  'title_resturant': 'レストラン',
  'text_open_Now': '今すぐ開きます。',
  'text_close': '今は閉まっています。',
  'text_special_mark': 'レビュー',
  'text_special_mark_error': 'メモを入力する',
  'text_reviews': 'コメント',
  'bt_leave_review': 'コメントを残す',
  'bt_leave_review_error': 'コメントを入力してください',
  'bt_leave_report': 'あなたの問題を残します。',
  'bt_leave_report_error': '問題を入力します。',
  'text_done_report': '問題は正常に送信されました',
  'text_see_more': '続きを読む',
  'text_done_review': 'あなたの意見は正常に記録されました',
  'text_under_reiew': 'あなたのレビュー。',
  'text_your_plan': '計画',
  'text_your_plan_select': 'あなたの仕事の計画が立てられています。',
  'bt_change_plan': '時刻を変更する',
  'bt_change_photo': '画像を変更する',
  'bt_profile_photo': '自分撮り。',
  'bt_add': '追加',
  'bt_cancel': 'キャンセル',
  'bt_check_out': '要求の確認',
  'bt_edit': '変更',
  'bt_edit_bran': '変更',
  'text_technical_support': 'テクニカルサポート',
  'text_add_branch': 'ブランチを追加する',
  'text_add_ticket': 'チケットを追加します。',
  'text_add_social': 'ネットワーク サイトを追加する',
  'text_social': 'ネットワーキングサイト',
  'hint_link': 'リンク',
  'link_error': 'このリンクは正しくありません。',
  'hint_subject': '件名',
  'hint_subject_error': 'テーマを入力する',
  'hint_details': '詳細',
  'hint_details_error': '詳細を入力',
  'bt_send': '送信',
  'hint_your_problem': 'ここに問題を追加します。',
  'text_forget_pass': 'パスワードを忘れたの?',
  'text_set_email': '電子メールを追加する',
  'text_enter_code': 'コードを入力してください!',
  'text_change_email': '電子メールを変更しますか?',
  'text_code': 'アイコン',
  'hint_code': '6 桁である必要があります。',
  'bt_sure': '確認',
  'text_enter_new_pass': '新しいパスワードを入力してください。',
  'text_new_pass': '新しいパスワード。',
  'text_success_change_pass': 'パスワードは正常に変更されました。 ',
  'side_be_delegate': 'マーケターになる。',
  'side_be_company': '会社になる',
  'side_be_affilator': 'マーケターになる。',
  'side_be_delegat': '会社になる',
  'side_contactus': '私たちと連絡を取る',
  'bt_add_plan': 'プランを追加します。',
  'bt_be_delegat': '会社になる',
  'text_choose-payment': '適切な支払い方法を選択する',
  'text_offline-payment': ' オフライン支払いの適切な方法を選択します。',
  'text_last_company': '最近追加されました',
  'text_review': 'コメント',
  'text_document': '会社の文書',
  'text_select_country_msg': '国と都市を選ぶ',
  'text_select_categore_msg': 'アイテムを選択していることを確認します。',

  'text_all_categories': 'すべての評価',
  'text_code_afflet': 'マーケターコード',
  'message': 'メッセージ',
  'message_warring_select_country_splash': '選択する必要があります',
  'big-text1': 'メールを受け取ってください。',
  'big-text2': 'コードを入力してください!',
  'big-text3': '新しい PIN を入力してください。',
  'again': '電子メールを変更しますか?',
  'number': 'ナショナル・アイデンティティ・ナンバー',
  'number_error': 'それは14の数字でなければなりません。',
  'face login': 'フェイスブックでサインインする',
  'google login': 'グーグル経由でログイン',
  'are you': 'あなたは。',
  'new account': '新しいアカウント',
  'language': '言語',
  'birth': '生年月日',
  'cont': '続けます',
  'sagel': '続けます',
  'pass': 'ピン',
  'enter-pass': '秘密の番号。',
  'new pass': '新しい秘密番号',
  're-pass': 'ピンの確認。',
  'phone': '電話',
  'change': '変更',
  'online': 'オンライン',
  'offline': 'オフライン',
  'pass_error': 'パスワードは 8 文字以上でなければなりません',

  'change-mail': 'メールの変更',

  'online-payment': 'オンラインピメント',
  'offline-payment': 'オフリン・ピメント',
  'how': 'どう',
  'bank': '銀行',
  'kash': '現金',

  'forgot_password?': 'パスワードを忘れましたか?',
  'please_wait': 'お待ちください。',
  'ok': 'わかりました',
  'email_error': '使用可能な電子メールを入力してください ',
  'details_error': '詳細は空にしないでください。',
  'code_error': 'コードは 6 桁以上にする必要があります。',
  'pay1': '支払いプランを選択します。',
  'pay2': '毎月のビジネスに適した時間を選択',
  'plan2': 'このプランを選択します。',
  'do2': 'スライダーの数 ',
  'do3': 'バナー数',
  'my-plan1': '計画',
  'e': 'それは間違いです。',
  'Loading': '読み込み',
  'text_pass_not_similer':  'PIN が同じではありません。',
  'text_p_select_photo':  '画像を選択してやり直す',
  'side_language_country':  '言語と国の変更',
  'bt_change': '変更',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'ウェブサイト',
  'other': '別の',
  'promo_code': '割引コード',
  'promo_code_used': '使用する割引コード',
  'promo_code_accept': '割引コードはそのままです。 ',
  'sub_total': '政府の能力',
  'discount': '割引',
  'price': '合計価格',
  'Saturday':'土曜日',
  'Sunday':'日曜日',
  'Monday':'月曜日',
  'Tuesday':'火曜日',
  'Wednesday':'水曜日',
  'Thursday':'木曜日',
  'Friday':'金曜日',
  'to':'宛先',


  'my-plan2': 'このプランを変更する',
  'my-plan3': '毎月のビジネスに選択したパッケージ',
  'eshtrak': '再サブスクライブ',
  'tagdeed': '更新',
  'bank1': '銀行振込用 \n  適切な情報',
  'bank2': '銀行口座に必要な情報',
  'bank_info_1': '銀行名',
  'bank_info_2': '口座番号',
  'bank_info_3': 'アカウント所有者の名前。',
  'bank_info_4': '支店名',
  'bank_info_5': 'スウィフトコード'
};
