// ignore: always_specify_types
const Map<String, String> ru = {

  'Download': 'загружать',
  'read': 'читать',
  'active_code': 'активный',
  'enter': 'входить',
  'enter_rate': 'пожалуйста, введите тариф',
  'Male': 'мужской',
  'Female': 'женский',
  'text_online-payment': 'выбрать подходящий способ онлайн-платежей',
  'quit_app': 'Вы уверены, что хотите бросить курить?',
  'Exit': 'выход',


  'text_select_time_msg':'Убедитесь, что вы выбираете время',
  'select_time':'Ограничение по времени',
  'show_photo':'Показать изображение',

  'select_country': 'Выберите состояние.',
  'select_company': 'Выберите компанию',
  'p_choose_country': 'Пожалуйста, выберите страну, в которую вы живете.',
  'p_choose_company': 'Какая компания хочет продлить подписку',
  'select_language': 'Выберите язык.',
  'bt_done': 'Был',
  'login': 'Входа',
  'search': 'Поиск',
  'search_error': 'Пожалуйста, введите слово для поиска.',
  'no_data': 'В настоящее время данных нет',
  'read_more': 'Читать чаще',
  'text_more': 'Больше',
  'read_less': 'читать меньше',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'А Вы?',
  'new_user': 'Новый пользователь',
  'Marketer': 'Маркетолог',
  'dealer': 'Компания',
  'question_login': 'У вас есть учетная запись?',
  'new_account': 'Новая учетная запись',
  'personal_info': 'Личная информация',
  'account_details': 'Сведения об учетной записи',
  'profile_photo': 'Селфи',
  'Company_photo': 'Логотип компании',
  'text_full_name': 'Полное имя.',
  'text_full_name_error': 'Электронная почта должна быть введена.',
  'hint_name': 'murafiq',
  'text_country': 'Поддержка правительства',
  'text_defalut_languages': 'Виртуальный язык',
  'text_resturant': 'Компании',
  'text_select_Pdf': 'Добавить файл',
  'text_df_language': 'Виртуальный язык',
  'text_gender': 'Тип',
  'text_birthDate': 'Дата рождения',
  'text_national_id': 'Идентификационный номер ',
  'text_email': 'Электронной почты',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'Пароль',
  'text_confirm_pass': 'Подтверждение пин-кода',
  'text_phone': 'Номер телефона',
  'text_days': 'Дни недели',
  'text_go': 'Перейти к',
  'text_phone_error': 'Этот телефон не прав.',
  'bt_continue': 'Продолжай.',
  'bt_submit': 'Добавить',
  'text_place_name': 'Название компании.',
  'text_place_name_error': 'Введите название компании.',
  'text_description': 'Детали',
  'text_description_error': 'Введите подробную информацию',
  'text_address': 'Адрес',
  'text_add_address': 'Добавить заголовок',
  'text_address_error': 'Введите адрес',
  'text_phone2': 'Еще один номер мобильного телефона.',
  'text_Tel': 'Номер земли',
  'text_fax': 'Номер факса',
  'text_fax_error': 'Номер факса неправильный.',
  'you_must_login_to_access': 'Пожалуйста, вопийся.',
  'you_must_sub': 'Вы должны подписка ',
  'company_photo': 'Фото компании',
  'text_workdays': 'Рабочие дни',
  'text_time_of_work': 'Часы работы',
  'text_category': 'Категории',
  'select_city': 'Выберите город.',
  'select_category': 'Выберите рейтинг',
  'select_sub_category': 'Выберите подкатеготову',
  'side_eshtrakaty': 'Подписки',
  'side_ads': 'Специальные объявления',
  'side_search_store': 'место поиска',
  'side_notifications': 'Уведомления',
  'side_edit_profile': 'Редактировать профиль',
  'side_edit_company': 'Монтажная компания',
  'side_mybranches': 'Мои ветви',
  'side_ask': 'Техническая поддержка?',
  'side_social': 'Социальные связи',
  'side_policy': 'Условия и положения',
  'side_total_client': 'Клиентов',
  'side_who_us': 'О нас',
  'side_logout': 'Выход',
  'side_customers': 'Клиентов',
  'title_resturant': 'Ресторан',
  'text_open_Now': 'Открыть сейчас',
  'text_close': 'Закрыть',
  'text_special_mark': 'Отзывов',
  'text_special_mark_error': 'Введите свои заметки',
  'text_reviews': 'Комментарии',
  'bt_leave_review': 'Я оставляю комментарий.',
  'bt_leave_review_error': 'Введите свой комментарий',
  'bt_leave_report': 'Оставьте свою проблему.',
  'bt_leave_report_error': 'Введите свою проблему.',
  'text_done_report': 'Проблема была успешно отправлена',
  'text_see_more': 'увидеть больше',
  'text_done_review': 'Ваше мнение было успешно записано',
  'text_under_reiew': 'Ваш отзыв отредактирован.',
  'text_your_plan': 'Планы',
  'text_your_plan_select': 'План был установлен для вашего бизнеса.',
  'bt_change_plan': 'Изменение пакета',
  'bt_change_photo': 'Изменить фотографию',
  'bt_profile_photo': 'фото профиля',
  'bt_add': 'Добавить',
  'bt_cancel': 'Отмена',
  'bt_check_out': 'Подтверждение запроса',
  'bt_edit': 'Обновление',
  'bt_edit_bran': 'Редактировать',
  'text_technical_support': 'Техническая поддержка',
  'text_add_branch': 'Добавить ветвь',
  'text_add_ticket': 'Добавить билет',
  'text_add_social': 'Добавить сайт связи',
  'text_social': ' Сетевой сайт',
  'hint_link': 'Ссылку',
  'link_error': 'Эта ссылка неверна.',
  'hint_subject': 'Тема',
  'hint_subject_error': 'Введите тему',
  'hint_details': 'Детали',
  'hint_details_error': 'Введите подробную информацию',
  'bt_send': 'Отправить',
  'hint_your_problem': 'Добавьте свою проблему здесь',
  'text_forget_pass': 'Ты забыла пароль?',
  'text_set_email': 'Добавить электронную почту',
  'text_enter_code': 'Пожалуйста, введите код!',
  'text_change_email': 'изменить это письмо?',
  'text_code': 'Код',
  'hint_code': 'Это должно быть шесть цифр.',
  'bt_sure': 'Подтверждение',
  'text_enter_new_pass': 'Пожалуйста, введите новый пароль',
  'text_new_pass': ' Новый пароль',
  'text_success_change_pass': 'Пароль успешно изменен',
  'side_be_delegate': 'Будь маркетологом.',
  'side_be_company': 'Быть компанией',
  'side_be_affilator': 'Будь маркетологом.',
  'side_be_delegat': 'Будь маркетологом.',
  'side_contactus': 'свяжитесь с нами',
  'bt_add_plan': 'добавить план',
  'bt_be_delegat': 'Будь маркетологом.',
  'text_choose-payment': 'Выберите правильный способ оплаты',
  'text_offline-payment': ' Выберите подходящий способ автономной оплаты',
  'text_last_company': 'Недавно добавлено',
  'text_review': 'Комментарии',
  'text_document': 'Документ компании',
  'text_select_country_msg': 'Убедитесь, что вы выбираете страну и город.',
  'text_select_categore_msg': 'Убедитесь, что вы выбираете элемент.',

  'text_all_categories': 'Все категории',
  'text_code_afflet': 'Код маркетолога',
  'message': 'Сообщение',
  'message_warring_select_country_splash': 'должны быть выбраны',
  'big-text1': 'Пожалуйста, получите письмо.',
  'big-text2': 'пожалуйста, введите код!',
  'big-text3': 'Пожалуйста, введите новый PIN-код.',
  'again': 'Изменить электронную почту?',
  'number': 'Номер национальной идентичности',
  'number_error': 'Это должно быть 14 номеров.',
  'face login': 'Log in with Facebook',
  'google login': 'Войти в систему через Google',
  'are you': 'А Вы?',
  'new account': 'Новая учетная запись',
  'language': 'Язык',
  'birth': 'Дата рождения',
  'cont': 'Продолжить',
  'sagel': 'Входа',
  'pass': 'Контактный',
  'enter-pass': 'ввести пароль',
  'new pass': 'новый пароль',
  're-pass': 'повторно ввести пароль',
  'phone': 'Телефон',
  'change': 'Изменить',
  'online': 'Онлайн',
  'offline': 'Автономных',
  'pass_error': 'Пароль должен быть более 8 символов',
  'change-mail': 'изменить электронную почту',
  'online-payment': 'онлайн-платеж',
  'offline-payment': 'офлайн-платеж',
  'how': 'Как',
  'bank': 'Банк',
  'kash': 'Наличными',
  'forgot_password?': 'Забыли пароль?',
  'please_wait': 'Подождите..',
  'ok': 'Хорошо',
  'email_error': 'Введите действительную электронную почту ',
  'details_error': 'Детали не должны быть пустыми.  ',
  'code_error': 'Код должен быть больше 6 цифр.',
  'pay1': 'Выберите свой план оплаты.',
  'pay2': 'Выберите подходящий пакет для вашей ежемесячной работы',
  'plan2': 'Выберите этот план',
  'do2': 'Количество слайдеров ',
  'do3': 'Количество Знамени',
  'my-plan1': 'Ваш план',
  'e': 'что-то пошло не так, пожалуйста, попробуйте еще раз',
  'Loading': 'Загрузка',
  'text_pass_not_similer':  'PIN-код не то же самое.',
  'text_p_select_photo':  'Выберите картинку и попробуйте еще раз.',
  'side_language_country':  'Изменение языка и страны',
  'bt_change': 'Чжан',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'Сайт',
  'other': 'Других',
  'promo_code': 'промо-код',
  'promo_code_used': ' Используемый код скидки',
  'promo_code_accept': ' Код скидки не поврежден. ',
  'sub_total': 'Суп Всего',
  'discount': 'Дискон',
  'price': 'Общая цена',
  'Saturday':'Суббота',
  'Sunday':'Воскресенье',
  'Monday':'Понедельник',
  'Tuesday':'Вторник',
  'Wednesday':'Среда',
  'Thursday':'Четверг',
  'Friday':'Пятница',
  'to':'Кому',



  'my-plan2': 'Изменить этот план',
  'my-plan3': 'Выбранный пакет для вашего ежемесячного бизнеса',
  'eshtrak': 'Повторное подписка',
  'tagdeed': 'Обновляется',
  'bank1': 'Информация, соответствующая банковским переводам',
  'bank2': 'Информация, необходимая для банковского счета',
  'bank_info_1': 'Название банка',
  'bank_info_2': 'номер счета',
  'bank_info_3': 'Имя владельца счета',
  'bank_info_4': 'название филиала',
  'bank_info_5': 'Код Свифта'

};
