// ignore: always_specify_types
const Map<String, String> tr = {


  'Download': 'Indir',
  'read': 'Okuma',
  'active_code': 'Etkin',
  'enter': 'Girin',
  'enter_rate': 'lütfen fiyat girin',
  'Male': 'Erkek',
  'Female': 'kadın',
  'text_online-payment': 'uygun çevrimiçi ödeme yöntemini seçin',
  'quit_app': 'Bırakmak istediğinden emin misin?',
  'Exit': 'Çıkış',

  'select_time':'Select Time',
  'show_photo':'Show Photo',


'text_select_time_msg':'Zamanı seçtiğinizden emin olun',
'select time':'Zaman sınırı',
'show photo':'fotoğraf göster',
'select_country': 'Bir eyalet seçin.',
'select_company': 'Bir şirket seçin',
'p_choose_country': 'Lütfen yaşadığınız ülkeyi seçin.',
'p_choose_company': '  Aboneliğinizi yenilemek istediğiniz herhangi bir şirket',
'select_language': 'Dil seçin',
'bt_done': 'Yapılır',
'login': 'Oturum açma',
'search': 'Arama',
'search_error': 'Lütfen arama için bir sözcük girin.',
'no_data': 'Şu anda veri yok',
'read_more': 'Daha fazla bilgi edinin',
'text_more': 'Daha fazla bilgi edinin',
'read_less': 'Daha az oku',
'al_murafiq': 'Al_Murafiq',
'are_you': 'Sen biliyor musun?',
'new_user': 'Yeni Kullanıcı',
'Marketer': 'Pazarlamacı',
'dealer': 'Satıcı',
'question_login': 'Zaten bir hesabınız var mı?',
'new_account': 'Yeni Hesap',
'personal_info': 'Kişisel Bilgiler',
'account_details': 'Hesap Ayrıntıları',
'profile_photo': 'Bir selfie.',
'Company_photo': 'Logo Şirketi',
'text_full_name': 'Tam Ad',
'text_full_name_error': 'E-posta girilmelidir',
'hint_name': 'murafiq',
'text_country': 'Ülke',
'text_defalut_languages': 'Sanal dil',
'text_resturant': 'Şirket',
'text_select_Pdf': 'Dosya ekleme',
'text_df_language': 'Sanal dil',
'text_gender': 'Türü',
'text_birthDate': 'Doğum tarihi',
'text_national_id': 'Kimlik Numarası',
'text_email': 'E‑posta',
'hint_email': 'murafiq@gmail.com',
'text_password': 'Gizli numara.',
'text_confirm_pass': 'Pin numarasını onaylama',
'text_phone': 'Telefon numarası',
'text_days': 'Günler',
'text_go': 'Git',
'text_phone_error': 'Bu telefon doğru değil.',
'bt_continue': 'Devam et.',
'bt_submit': 'Ekle',
'text_place_name': 'Şirketin adı.',
'text_place_name_error': 'Şirket adını girin.',
'text_description': 'Açıklama',
'text_description_error': 'Ayrıntıları girin',
'text_address': 'Adres',
'text_add_address': 'adres ekleme',
'text_address_error': 'Adres girme',
'text_phone2': 'Başka bir cep telefonu numarası.',
'text_Tel': 'Arsa numarası',
'text_fax': 'Faks numarası',
'text_fax_error': 'Faks numarası yanlış.',
'you_must_login_to_access': 'Lütfen oturum açın.',
'you_must_sub': 'Abone olmalısınız ',
'company_photo': 'Şirket Fotoğrafı',
'text_workdays': 'Çalışma günleri',
'text_time_of_work': 'Çalışma saatleri',
'text_category': 'Kategori',
'select_city': 'Bir şehir seçin.',
'select_category': 'Derecelendirme seç',
'select_sub_category': 'Bir dal derecelendirmesi seçin.',
'side_eshtrakaty': 'Abonelik',
'side_ads': 'Özel duyurular',
'side_search_store': 'Arama geçmişi',
'side_edit_profile': 'Hesabı ayarlama',
'side_notifications': 'Bildirim',
'side_edit_company': 'Şirket değişikliği',
'side_mybranches': 'Dallarım.',
'side_ask': 'Teknik destek',
'side_policy': 'Hüküm ve hükümler',
'side_social': 'Sosyal Bağlantılar',
'side_total_client': 'Müşteri',
'side_who_us': 'Biz kimiz ki',
'side_logout': 'Oturum kapatma',
'side_customers': 'Müşteri',
'title_resturant': 'Restoran',
'text_open_Now': 'Şimdi aç',
'text_close': 'Şimdi kapandı.',
'text_special_mark': 'Notlar',
'text_special_mark_error': 'Notlarınızı girme',
'text_reviews': 'Yorum',
'bt_leave_review': 'Bir yorum bırakıyorum.',
'bt_leave_review_error': 'Açıklamanızı girin',
'bt_leave_report': 'Sorununu bırak.',
'bt_leave_report_error': 'Sorununuzu girin.',
'text_done_report': 'Sorun başarıyla gönderildi.',
'text_see_more': 'Daha fazla bilgi edinin',
'text_done_review': 'Görüşünüz başarıyla kaydedildi',
'text_under_reiew': 'yorumunuz düzenlendi.',
'text_your_plan': 'Plan',
'text_your_plan_select': 'İşletmeniz için bir plan belirlendi.',
'bt_change_plan': 'Paketi değiştirme',
'bt_change_photo': 'Fotoğrafları değiştirme',
'bt_profile_photo': 'Profil resmi',
'bt_add': 'Ekle',
'bt_cancel': 'İptal',
'bt_check_out': 'İsteği onayla',
'bt_edit': 'Güncelleştirme',
'bt_edit_bran': 'Değiştirmek',
'text_technical_support': 'Teknik destek',
'text_add_branch': 'Dal ekleme',
'text_add_ticket': 'Bilet ekleme',
'text_add_social': 'İletişim sitesi ekleme',
'text_social': 'Ağ sitesi',
'hint_link': 'Bağlantı',
'link_error': 'Bu bağlantı yanlış.',
'hint_subject': 'Konu',
'hint_subject_error': 'konu girme',
'hint_details': 'Şey',
'hint_details_error': 'Ayrıntıları girme',
'bt_send': 'Gönder',
'hint_your_problem': 'Sorununuzu buraya ekleyin',
'text_forget_pass': 'Şifreyi unuttun mu?',
'text_set_email': 'E-postanızı ekleme',
'text_enter_code': 'Lütfen kodu girin.',
'text_change_email': 'E-postayı değiştirmek mi?',
'text_code': 'Kod',
'hint_code': 'Altı haneli olmalı.',
'bt_sure': 'Onay',
'text_enter_new_pass': 'Lütfen yeni parolayı girin',
'text_new_pass': 'yeni parola',
'text_success_change_pass': 'Parola başarıyla değiştirildi',
'side_be_delegate': 'Pazarlamacı ol.',
'side_be_company': 'Şirket olun',
'side_be_affilator': 'Pazarlamacı ol.',
'side_be_delegat': 'Şirket olun',
'side_contactus': 'Bizimle iletişime geçin',
'bt_add_plan': 'planınızı ekleme',
'bt_be_delegat': 'Pazarlamacı ol.',
'text_choose-payment': 'Doğru ödeme yöntemini seçin',
'text_offline-payment': '  Uygun Çevrimdışı ödeme yöntemini seçin',
'text_last_company': 'Son eklenen',
'text_review': 'Yorum',
'text_document': 'şirket belgesi',
'text_select_country_msg': 'Ülkeyi ve şehri seçtiğinizden emin olun.',
'text_select_categore_msg': 'Öğeyi seçtiğinizden emin olun.',

'text_all_categories': 'Tüm Kategoriler',
'text_code_afflet': 'Pazarlamacı Kodu',
'message': 'İleti',
'message_warring_select_country_splash': 'seçilmelidir',
'big-text1': 'Lütfen e-postayı alın.',
'big-text2': 'Lütfen kodu girin.',
'big-text3': 'Lütfen yeni PIN\'i girin.',
'again': 'E-posta değiştirilir mi?',
'number': 'Ulusal Kimlik Numarası ',
'number_error': '14 numara olmalı.',
'face login': 'Facebook\'ta oturum açma',
'google login': 'Google üzerinden oturum açın',
'are you': 'Sen biliyor musun?',
'new account': 'Yeni hesap',
'language': 'Dil',
'birth': 'Doğum tarihi',
'cont': 'Devam',
'sagel': 'Oturum açma',
'pass': 'Pin',
'enter-pass': 'parola girme',
'new pass': 'yeni parola',
're-pass': 'parolayı yeniden girme',
'phone': 'Telefon',
'change': 'Değiştirmek',
'online': 'online',
'offline': 'Çevrimdışı',
'pass_error': 'Parola 8 karakterden fazla olmalıdır',
'change-mail': 'e-postayı değiştirme',
'online-payment': 'online ödeme',
'offline-payment': 'çevrimdışı ödeme',
'how': 'Nasıl',
'bank': 'banka',
'kash': 'Nakit',
'forgot_password?': 'Şifreyi mi unuttunuz?',
'please_wait': 'Lütfen bekleyin..',
'ok': 'Tamam',
'email_error': 'Geçerli bir e-posta girme ',
'details_error': 'Detaylar boş olmamalı. ',
'code_error': 'Kod 6 basamaktan fazla olmalıdır.',
'pay1': 'Ödeme planınızı seçin.',
'pay2': 'Aylık çalışmanız için doğru paketi seçin',
'plan2': 'Bu planı seçin.',
'do2': 'Kaydırıcı Sayısı ',
'do3': 'Başlık Sayısı',
'my-plan1': 'Planınız',
'e': 'bir şeyler ters gitti lütfen yeniden deneyin',
'Loading': ' Yükleme',
'text_pass_not_similer':  'PIN aynı değil.',
'text_p_select_photo':  'Bir resim seçin ve yeniden deneyin.',
'side_language_country':  'Değişen Dil ve Ülke',
'bt_change': 'Değiştirmek',
'facebook': 'facebook',
'twitter': 'twitter',
'instagram': 'instagram',
'whatsapp': 'whatsapp',
'snapshat': 'snapshat',
'googleplus': 'googleplus',
'website': 'Web sitesi',
'other': 'Diğer',
'promo_code': 'Kod promosyonu',
'promo_code_used': 'Kullanılan iskonto kodu',
'promo_code_accept': 'İndirim kodu bozulmamış.',
'sub_total': 'alt toplam',
'discount': 'Indirim',
'price': 'Toplam Fiyat',
'Saturday':'Cumartesi',
'Sunday':'Pazar',
'Monday':'Pazartesi',
'Tuesday':'Salı',
'Wednesday':'Çarşamba',
'Thursday':'Perşembe',
'Friday':'Cuma',
'to':'Hedef',

'my-plan2': 'Bu planı değiştir',
'my-plan3': 'Aylık işletmeniz için seçilen paket',
'eshtrak': 'Yeniden abone ol',
'tagdeed': 'Yenilemek',
'bank1': 'Banka havalesi için uygun bilgiler',
'bank2': 'Banka hesabı için gerekli bilgiler',
'bank_info_1': 'Banka adı',
'bank_info_2': 'hesap numarası',
'bank_info_3': 'Hesap sahibinin adı',
'bank_info_4': 'dal adı',
'bank_info_5': 'Swift Kodu'





};
