// ignore: always_specify_types
const Map<String, String> ur = {

  'Download': 'ڈاؤن لوڈ',
  'read': 'پڑھیں',
  'active_code': 'فعال',
  'enter': 'داخل',
  'enter_rate': 'براہ کرم شرح داخل کریں',
  'Male': 'مرد',
  'Female': 'خواتین',
  'text_online-payment': 'آن لائن ادائیگی کا مناسب طریقہ منتخب کریں',
  'quit_app': 'کیا آپ کو یقین ہے کہ آپ باہر نکلنا چاہتے ہیں؟',
  'Exit': 'خروج',


  'text_select_time_msg':'اثبات کریں کہ آپ وقت کا انتخاب کرتے ہیں',
  'select_time':'وقت کی حد',
  'show_photo':'تصویر نمایش کریں',
  'select_country': 'ریاست کا انتخاب کریں۔',
  'select_company': 'کمپنی کا انتخاب کریں',
  'p_choose_country': 'براہ کرم اس ملک کا انتخاب کریں جس میں آپ رہتے ہیں۔',
  'p_choose_company': 'کون سی کمپنی ہے جو اپنی رکنیت کی تجدید کرنا چاہتی ہے؟',
  'select_language': 'زبان کا انتخاب کریں۔',
  'bt_done': 'کیا',
  'login': 'درج کريں',
  'search': 'تلاش',
  'search_error': 'تلاش کے لیے ایک لفظ داخل کریں۔',
  'no_data': 'فی الحال کوئی کوائف نہیں',
  'read_more': 'مزید پڑھیں',
  'text_more': 'مزید',
  'read_less': 'کم پڑھیں',
  'al_murafiq': 'Al_Murafiq',
  'are_you': 'تم ہو؟',
  'new_user': 'نیا صارف',
  'Marketer': 'مسوق',
  'dealer': 'ایک کمپنی',
  'question_login': 'پہلے ہی ایک اکاؤنٹ ہے؟',
  'new_account': 'نیا اکاؤنٹ',
  'personal_info': 'ذاتی معلومات',
  'account_details': 'اکاؤنٹ کی تفصیلات',
  'profile_photo': 'پروفائل فوٹو',
  'Company_photo': 'لوگو کمپنی',
  'text_full_name': 'پورا نام.',
  'text_full_name_error': 'ای میل درج ہونا چاہیے۔',
  'hint_name': 'murafiq',
  'text_country': 'ملک',
  'text_defalut_languages': 'مجازی زبان',
  'text_resturant': 'کمپنی',
  'text_select_Pdf': 'مسل ا ضافہ کریں',
  'text_df_language': 'مجازی زبان',
  'text_gender': 'قسم',
  'text_birthDate': 'تاريخ پيدائش',
  'text_national_id': 'شناخت نمبر ',
  'text_email': ' ای میل',
  'hint_email': 'murafiq@gmail.com',
  'text_password': 'خفیہ نمبر.',
  'text_confirm_pass': 'پن نمبر کی تصدیق کریں',
  'text_phone': 'فون نمبر',
  'text_days': 'دن',
  'text_go': 'میرے پاس جاؤ.',
  'text_phone_error': 'یہ فون ٹھیک نہیں ہے۔',
  'bt_continue': 'جاری رکھیں',
  'bt_submit': 'جمع کرانا',
  'text_place_name': 'نام کمپنی',
  'text_place_name_error': 'کمپنی کا نام درج کریں۔',
  'text_description': 'تفصیلات',
  'text_description_error': 'تفصیلات درج کریں',
  'text_address': 'عنوان',
  'text_add_address': 'عنوان ا ضافہ کریں',
  'text_address_error': 'ایک پتہ داخل کریں',
  'text_phone2': 'ایک اور موبائل نمبر.',
  'text_Tel': 'زمین نمبر',
  'text_fax': 'فیکس نمبر',
  'text_fax_error': 'فیکس نمبر غلط ہے۔',
  'you_must_login_to_access': 'براہ کرم سائن ان کریں۔ ',
  'you_must_sub': 'آپ کو سبسکرپشن کرنی چاہیے ',
  'company_photo': 'کمپنی فوٹو',
  'text_workdays': 'کام کے دن',
  'text_time_of_work': 'اوقات کار',
  'text_category': 'زمرے',
  'select_city': 'شہر کا انتخاب کریں۔',
  'select_category': 'درجہ بندی کا انتخاب کریں',
  'select_sub_category': 'ذیلی درجہ بندی کا انتخاب کریں',
  'side_eshtrakaty': 'سبسکرپشنز',
  'side_ads': 'خصوصی اعلانات',
  'side_search_store': 'تلاش کی جگہ',
  'side_edit_profile': 'پروفائل تدوین کریں',
  'side_edit_company': 'کمپنی تدوین کریں',
  'side_notifications': 'اطلاعات',
  'side_mybranches': 'میری شاخیں',
  'side_ask': 'تکنیکی معاونت',
  'side_social': 'سوشل میڈیا',
  'side_policy': 'شرائط و ضوابط',
  'side_total_client': 'کسٹمر',
  'side_who_us': 'ہماری بارے ميں',
  'side_logout': 'لاگ آؤٹ',
  'side_customers': 'گاہکوں',
  'title_resturant': 'Resturant',
  'text_open_Now': 'اب کھولیں',
  'text_close': 'بند',
  'text_special_mark': 'جائزہ',
  'text_special_mark_error': 'اپنے نوٹ درج کریں',
  'text_reviews': 'تبصرے',
  'bt_leave_review': 'میں ایک تبصرہ چھوڑتا ہوں.',
  'bt_leave_review_error': 'اپنا تبصرہ چھوڑیں۔',
  'bt_leave_report': 'اپنا مسئلہ چھوڑ دیں.',
  'bt_leave_report_error': 'اپنا مسئلہ درج کریں۔',
  'text_done_report': 'مسئلہ کامیابی سے بھیج دیا گیا',
  'text_see_more': 'مزید پڑھیں',
  'text_done_review': 'آپ کی رائے کامیابی سے ریکارڈ کر لی گئی ہے',
  'text_under_reiew': 'آپ کا جائزہ ترمیم شدہ.',
  'text_your_plan': 'منصوبے',
  'text_your_plan_select': 'آپ کے کاروبار کے لئے ایک منصوبہ طے کیا گیا ہے۔',
  'bt_change_plan': 'یہ منصوبہ تبدیل کریں',
  'bt_change_photo': 'تصویر تبدیل کریں',
  'bt_profile_photo': 'پروفائل فوٹو',
  'bt_add': 'اضافہ',
  'bt_cancel': 'منسوخ',
  'bt_check_out': 'درخواست کی تصدیق کریں',
  'bt_edit': 'تازہ کاری',
  'bt_edit_bran': 'تدوین',
  'text_technical_support': 'تکنیکی معاونت',
  'text_add_branch': 'ایک شاخ ا ضافہ کریں',
  'text_add_ticket': 'ٹکٹ شامل کریں',
  'text_add_social': 'مواصلاتی سائٹ ا ضافہ کریں',
  'text_social': 'نیٹ ورکنگ سائٹ',
  'hint_link': 'ربط',
  'link_error': 'یہ ربط غلط ہے۔',
  'hint_subject': 'موضوع',
  'hint_subject_error': 'ایک تھیم داخل کریں',
  'hint_details': 'تفصیلات',
  'hint_details_error': 'تفصیلات درج کریں',
  'bt_send': 'بھیجیں',
  'hint_your_problem': 'اپنا مسئلہ یہاں شامل کریں',
  'text_forget_pass': 'پاس ورڈ بھول جائیں؟',
  'text_set_email': 'اپنا ای میل سیٹ کریں',
  'text_enter_code': 'براہ کرم کوڈ درج کریں!',
  'text_change_email': 'یہ ای میل تبدیل کریں؟',
  'text_code': 'کوڈ',
  'hint_code': 'یہ چھ عدد ہونا ہے۔',
  'bt_sure': 'تصدیق',
  'text_enter_new_pass': 'نیا پاس ورڈ داخل کریں',
  'text_new_pass': 'نیا پاس ورڈ',
  'text_success_change_pass': 'پاس ورڈ کامیابی سے تبدیل کر دیا گیا',
  'side_be_delegate': 'تفویض کریں',
  'side_be_company': 'کمپنی ہو',
  'side_be_affilator':'تفویض کریں',
  'side_be_delegat': 'تفویض کریں',
  'side_contactus': 'ہم سے رابطہ کریں',
  'bt_add_plan': 'منصوبہ ا ضافہ کریں ',
  'bt_be_delegat': 'تفویض کریں',
  'text_choose-payment': 'ادائیگی کے مناسب طریقے کا انتخاب کریں',
  'text_offline-payment': '  آف لائن ادائیگی کا مناسب طریقہ انتخاب کریں',
  'text_last_company': 'حال ہی میں اضافہ کیا گیا',
  'text_review': 'جائزہ',
  'text_document': 'کمپنی کی دستاویز',
  'text_select_country_msg': 'ملک اور شہر کا انتخاب یقینی بنائیں',
  'text_select_categore_msg': 'زمرہ انتخاب یقینی بنائیں',

  'text_all_categories': 'تمام زمرہ جات',
  'text_code_afflet': ' کوڈ',
  'message': 'پیغامات',
  'message_warring_select_country_splash': 'منتخب کیا جانا چاہیے',
  'big-text1': 'براہ کرم ای میل درج کریں',
  'big-text2': 'براہ کرم کوڈ درج کریں!',
  'big-text3': 'براہ کرم نیا پاس ورڈ درج کریں',
  'again': 'ای میل تبدیل کریں؟',
  'number': 'قومی شناختی نمبر',
  'number_error': 'اس کے 14 نمبر ہونے ہیں۔',
  'face login': 'فیس بک کے ساتھ لاگ ان کریں',
  'google login': 'گوگل کے ساتھ لاگ ان کریں',
  'are you': 'کیا تم ہو ؟',
  'new account': 'نیا اکاؤنٹ',
  'language': 'زبان',
  'birth': 'تاريخ پيدائش',
  'cont': 'جاری رکھیں',
  'sagel': 'درج کريں',
  'pass': 'لفظ پاس کریں ',
  'enter-pass': 'پاس لفظ درج کریں ',
  'new pass': 'نیا پاس لفظ ',
  're-pass': 'پاس ورڈ پھر درج کریں ',
  'phone': 'فون',
  'change': 'تبدیل',
  'online': 'آن لائن',
  'offline': 'آف لائن',
  'pass_error': 'پاس ورڈ 8 کریکٹر سے زیادہ ہونا چاہیے',
  'change-mail': 'ای میل تبدیل کریں',
  'online-payment': 'آن لائن ادائیگی',
  'offline-payment': 'آف لائن ادائیگی',
  'how': 'کیسے',
  'bank': 'بینک',
  'kash': 'نقد',
  'forgot_password?': 'پاس ورڈ بھول گئے؟',
  'please_wait': 'براۓ مہربانی انتظار کريں..',
  'ok': 'ٹھیک',
  'email_error': 'ایک درست ای میل درج کریں ',
  'details_error': 'تفصیلات خالی نہیں ہونا چاہئے۔ ',
  'code_error': 'کوڈ 6 ہندسوں سے زیادہ ہونا چاہیے۔',
  'pay1': 'اپنی ادائیگی کے منصوبے کا انتخاب کریں۔',
  'pay2': 'آپ کے ماہانہ کام کے لئے چوس تھی اپرپریات باکیج',
  'plan2': 'اپنے ماہانہ کام کے لیے صحیح پیکج کا انتخاب کریں',
  'do2': 'سلائیڈر کی تعداد ',
  'do3': 'بینر کی تعداد',
  'my-plan1': 'آپ کا منصوبہ',
  'e': 'کچھ غلط ہو گیا براہ کرم دوبارہ کوشش کریں',
  'Loading': 'لوڈنگ',
  'text_pass_not_similer':  'پاس ورڈ مشابہ نہیں',
  'text_p_select_photo':  'تصویر کا انتخاب کریں پھر کوشش کریں',
  'side_language_country':  'زبان اور ملک تبدیل کرنا',
  'bt_change': 'تبدیل',
  'facebook': 'facebook',
  'twitter': 'twitter',
  'instagram': 'instagram',
  'whatsapp': 'whatsapp',
  'snapshat': 'snapshat',
  'googleplus': 'googleplus',
  'website': 'ویب سائٹ',
  'other': 'دیگر',
  'promo_code': 'پرومو کوڈ',
  'promo_code_used': 'ڈسکاؤنٹ کوڈ استعمال کیا جاتا ہے',
  'promo_code_accept': 'ڈسکاؤنٹ کوڈ برقرار ہے۔',
  'sub_total': 'ذیلی کل',
  'discount': 'رعایت',
  'price': 'کل قیمت',
  'Saturday':'ہفتہ',
  'Sunday':'اتوار',
  'Monday':'پیر',
  'Tuesday':'منگل',
  'Wednesday':'بدھ',
  'Thursday':'جمعرات',
  'Friday':'جمعہ',
  'to':'ميرے ليۓ',


  'my-plan2': 'یہ منصوبہ تبدیل کریں',
  'my-plan3': 'آپ کے ماہانہ کاروبار کے لیے منتخب پیکج',
  'eshtrak': 'دوبارہ سبسکرائب کریں',
  'tagdeed': 'تجدید',
  'bank1': 'بینک منتقلی کے لئے مناسب معلومات',
  'bank2': 'بینک اکاؤنٹ کے لئے درکار معلومات',
  'bank_info_1': 'بینک نام',
  'bank_info_2': 'اکاؤنٹ نمبر',
  'bank_info_3': 'اکاؤنٹ مالک کا نام',
  'bank_info_4': 'اکاؤنٹ مالک',
  'bank_info_5': 'سوئفٹ کوڈ'
};
