// ignore: always_specify_types
const Map<String, String> zh ={
  'Download': '下载',
  'read': '读',
  'active_code': '积极r',
  'enter': '进入',
  'enter_rate': '请输入速率',
  'Male': '雄',
  'Female': '女性',
  'text_online-payment': '选择适当的在线支付方式',
  'quit_app': '你确定要辞职吗？',
  'Exit': '退出',


  'select_time':'Select Time',
  'show_photo':'Show Photo',


'text_select_time_msg':'确保您选择时间',
'select time':'时间限制',
'show photo':'显示图像',
'select_country': '选择状态。',
'select_company': '选择公司',
'p_choose_country': '请选择您居住的国家/',
'p_choose_company': '哪家公司想要续订订阅?',
'select_language': '选择语言',
'bt_done': '是',
'login': '登录',
'search': '搜索',
'search_error': '请输入一个单词进行搜索。',
'no_data': '目前没有数据',
'read_more': '阅读更多',
'text_more': '摩尔',
'read_less': '红色不是',
'al_murafiq': 'Al_Murafiq',
'are_you': '你是？',
'new_user': '新用户',
'Marketer': '营销',
'dealer': '一家公司',
'question_login': '你有帐户吗？',
'new_account': '新帐户',
'personal_info': '个人信息',
'account_details': '帐户详细信息',
'profile_photo': '自拍',
'Company_photo': '徽标公司',
'text_full_name': '全名',
'text_full_name_error': '必须输入电子邮件。',
'hint_name': 'murafiq',
'text_country': '政府的支持',
'text_defalut_languages': '虚拟语言',
'text_resturant': '公司',
'text_select_Pdf': '添加文件',
'text_df_language': '虚拟语言',
'text_gender': '类型',
'text_birthDate': '出生日期',
'text_national_id': '身份证号码',
'text_email': '电子邮件',
'hint_email': 'murafiq@gmail.com',
'text_password': '密码',
'text_confirm_pass': '确认引脚编号',
'text_phone': '电话号码',
'text_days': '日',
'text_go': '转到(G)',
'text_phone_error': '这个电话不对。',
'bt_continue': '继续。',
'bt_submit': '添加',
'text_place_name': '公司名称。',
'text_place_name_error': '输入公司名称。',
'text_description': '细节',
'text_description_error': '输入详细信息',
'text_address': '地址',
'text_add_address': '添加标题',
'text_address_error': '输入地址',
'text_phone2': '另一个手机号码。',
'text_Tel': '土地编号',
'text_fax': '传真号码',
'text_fax_error': '传真号码不正确。',
'you_must_login_to_access': '请登录。 ',
'you_must_sub': '您必须订阅 ',
'company_photo': '公司照片',
'text_workdays': '工作日',
'text_time_of_work': '工作时间',
'text_category': '类别',
'select_city': '选择一个城市。',
'select_category': '选择评级',
'select_sub_category': '选择子分类',
'side_eshtrakaty': '订阅',
'side_ads': '特别公告',
'side_search_store': '搜索历史记录',
'side_edit_profile': '调整帐户',
'side_notifications': '通知',
'side_edit_company': '公司修改',
'side_mybranches': '我的分行',
'side_ask': '技术支持',
'side_social': '社交链接',
'side_policy': '条款和规定',
'side_total_client': '客户总数',
'side_who_us': '关于我们',
'side_logout': '注销',
'side_customers': '客户',
'title_resturant': '餐厅',
'text_open_Now': '立即打开',
'text_close': '关闭',
'text_special_mark': '评论',
'text_special_mark_error': '输入您的笔记',
'text_reviews': '评论',
'bt_leave_review': '我发表评论。',
'bt_leave_review_error': '输入您的评论',
'bt_leave_report': '留下你的问题。',
'bt_leave_report_error': '输入您的问题。',
'text_done_report': '问题已成功发送',
'text_see_more': '阅读更多',
'text_done_review': '您的意见已被成功记录',
'text_under_reiew': '您的评论已编辑。',
'text_your_plan': '计划',
'text_your_plan_select': '已为您的业务制定了计划。',
'bt_change_plan': '更改此计划',
'bt_change_photo': '更改图像',
'bt_profile_photo': '个人资料图片',
'bt_add': '添加',
'bt_cancel': '取消',
'bt_check_out': '确认请求',
'bt_edit': '更新',
'bt_edit_bran': '修改',
'text_technical_support': '技术支持',
'text_add_branch': '添加分支',
'text_add_ticket': '添加票证',
'text_add_social': '添加社交',
'text_social': '网络站点',
'hint_link': '链接',
'link_error': '此链接不正确。',
'hint_subject': '主题',
'hint_subject_error': '输入主题',
'hint_details': '细节',
'hint_details_error': '输入详细信息',
'bt_send': '发送',
'hint_your_problem': '在此处添加您的问题',
'text_forget_pass': '你忘了密码吗？',
'text_set_email': '添加您的电子邮件',
'text_enter_code': '请输入代码！',
'text_change_email': '更改此电子邮件？',
'text_code': '代码',
'hint_code': '它必须是六位数。',
'bt_sure': '确认',
'text_enter_new_pass': '请输入新密码',
'text_new_pass': '新密码',
'text_success_change_pass': '密码已成功更改',
'side_be_delegate': '做一个营销人员。',
'side_be_company': '成为一家公司',
'side_be_affilator': '做一个营销人员。',
'side_be_delegat': '成为代表',
'side_contactus': '联系我们',
'bt_add_plan': '添加计划',
'bt_be_delegat': '做一个营销人员。',
'text_choose-payment': '选择合适的支付方式',
'text_offline-payment': '  选择适当的离线支付方式',
'text_last_company': '最近添加',
'text_review': '评论',
'text_document': '公司文件',
'text_select_country_msg': '确保你选择的国家和城市。',
'text_select_categore_msg': '请确保您选择的项目。',

'text_all_categories': '所有评级',
'text_code_afflet': '营销代码',
'message': '消息',
'message_warring_select_country_splash': '必须选择',
'big-text1': '请收到电子邮件。',
'big-text2': '请输入代码。',
'big-text3': '请输入新的PIN码。',
'again': '更改电子邮件？',
'number': '国家身份号码',
'number_error': '它必须是14个数字。',
'face login': '使用脸谱网登录',
'google login': '通过谷歌登录',
'are you': '你是？',
'new account': '新帐户',
'language': '语言',
'birth': '出生日期',
'cont': '继续',
'sagel': '登录',
'pass': '密码',
'enter-pass': '输入密码',
'new pass': '新密码',
're-pass': '重新输入密码',
'phone': '电话',
'change': '改变',
'online': '在线',
'offline': '离线',
'pass_error': '密码必须超过 8 个字符',
'change-mail': '更改电子邮件',
'online-payment': '在线支付',
'offline-payment': '离线付款',
'how': '如何',
'bank': '银行',
'kash': '现金',
'forgot_password?': '忘记密码？',
'please_wait': '请稍候。。',
'ok': '好',
'email_error': '输入有效电子邮件 ',
'details_error': '细节不应该是空的。 ',
'code_error': '代码必须超过 6 位。',
'pay1': '选择您的付款计划。',
'pay2': '为您的月度工作选择合适的套餐',
'plan2': '选择此计划。',
'do2': '滑块数量',
'do3': '横幅数量',
'my-plan1': '您的计划',
'e': '出了问题，请稍后再试',
'Loading': '加载',
'text_pass_not_similer':  '引脚不一样。',
'text_p_select_photo':  '选一张图片再试一次。',
'side_language_country':  '更改语言和国家/地区',
'bt_change': '改变',
'facebook': 'facebook',
'twitter': 'twitter',
'instagram': 'instagram',
'whatsapp': 'whatsapp',
'snapshat': 'snapshat',
'googleplus': 'googleplus',
'website': '网站',
'other': '其他',
'promo_code': '促销代码',
'promo_code_used': '使用折扣代码',
'promo_code_accept': '折扣代码完好无损。 ',
'sub_total': '子总数',
'discount': '折扣',
'price': '总价',
'Saturday':'星期六',
'Sunday':'星期日',
'Monday':'星期一',
'Tuesday':'星期二',
'Wednesday':'星期三',
'Thursday':'星期四',
'Friday':'星期五',
'to':'自',

'my-plan2': '更改此计划',
'my-plan3': '每月业务的选定套餐',
'eshtrak': '重新订阅',
'tagdeed': '更新',
'bank1': '适用于银行转账的信息',
'bank2': '银行账户所需的信息',
'bank_info_1': '银行名称',
'bank_info_2': '帐号',
'bank_info_3': '帐户所有者的名称',
'bank_info_4': 'branch name',
'bank_info_5': '斯威夫特代码'




};
